interface Config {
  MINIMUM_VERSION: string | undefined;
  IGNORE_MINIMUM_VERSION: string | undefined;
  WEBPACK_WEB_PORT: string | undefined;
  WEBPACK_ELECTRON_PORT: string | undefined;
  WEB_SERVER_PORT: string | undefined;
  LBRY_WEB_API: string | undefined;
  LBRY_WEB_API_NO_CF: string | undefined;
  LBRY_WEB_PUBLISH_API: string | undefined;
  LBRY_WEB_PUBLISH_API_V2: string | undefined;
  LBRY_WEB_PUBLISH_API_V3: string | undefined;
  LBRY_WEB_PUBLISH_API_V4: string | undefined;
  LBRY_API_URL: string | undefined;
  LBRY_WEB_BUFFER_API: string | undefined;
  SEARCH_SERVER_API: string | undefined;
  SEARCH_SERVER_API_ALT: string | undefined;
  COMMENT_SERVER_API: string | undefined;
  LIVESTREAM_SERVER_API: string | undefined;
  SHORT_URL_API: string | undefined;
  SOCKETY_SERVER_API: string | undefined;
  LOCALE_API: string | undefined;
  GEO_BLOCK_API: string | undefined;
  WELCOME_VERSION: string | undefined;
  DOMAIN: string | undefined;
  SHARE_DOMAIN_URL: string | undefined;
  URL: string | undefined;
  RECSYS_ENDPOINT: string | undefined;
  RECSYS_FYP_ENDPOINT: string | undefined;
  IMAGE_PROXY_URL: string | undefined;
  THUMBNAIL_CDN_URL: string | undefined;
  THUMBNAIL_CARDS_CDN_URL: string | undefined;
  THUMBNAIL_HEIGHT: string | undefined;
  THUMBNAIL_HEIGHT_POSTER: string | undefined;
  THUMBNAIL_WIDTH: string | undefined;
  THUMBNAIL_WIDTH_POSTER: string | undefined;
  THUMBNAIL_QUALITY: string | undefined;
  THUMBNAIL_CDN_SIZE_LIMIT_BYTES: string | undefined;
  PLAYER_SERVER: string | undefined;
  SITE_TITLE: string | undefined;
  SITE_NAME: string | undefined;
  SITE_DESCRIPTION: string | undefined;
  SITE_HELP_EMAIL: string | undefined;
  TWITTER_ACCOUNT: string | undefined;
  LOGO_TITLE: string | undefined;
  LOGO: string | undefined;
  LOGO_WHITE_TEXT: string | undefined;
  LOGO_DARK_TEXT: string | undefined;
  AVATAR_DEFAULT: string | undefined;
  MISSING_THUMB_DEFAULT: string | undefined;
  OG_TITLE_SUFFIX: string | undefined;
  OG_HOMEPAGE_TITLE: string | undefined;
  OG_IMAGE_URL: string | undefined;
  YRBL_HAPPY_IMG_URL: string | undefined;
  YRBL_SAD_IMG_URL: string | undefined;
  LOGIN_IMG_URL: string | undefined;
  SITE_CANONICAL_URL: string | undefined;
  DEFAULT_LANGUAGE: string | undefined;
  AUTO_FOLLOW_CHANNELS: string | undefined;
  UNSYNCED_SETTINGS: string | undefined;
  FARCASTER_ACCOUNT_ASSOC_HEADER: string | undefined;
  FARCASTER_ACCOUNT_ASSOC_PAYLOAD: string | undefined;
  FARCASTER_ACCOUNT_ASSOC_SIGNATURE: string | undefined;
  FARCASTER_ICON_URL: string | undefined;
  FARCASTER_SPLASH_IMAGE_URL: string | undefined;
  FARCASTER_SPLASH_BACKGROUND_COLOR: string | undefined;
  FARCASTER_HERO_IMAGE_URL: string | undefined;
  ENABLE_COMMENT_REACTIONS: boolean;
  ENABLE_FILE_REACTIONS: boolean;
  ENABLE_CREATOR_REACTIONS: boolean;
  ENABLE_NO_SOURCE_CLAIMS: boolean;
  ENABLE_PREROLL_ADS: boolean;
  CHANNEL_STAKED_LEVEL_VIDEO_COMMENTS: string | undefined;
  CHANNEL_CREATION_LIMIT: string | undefined;
  WEB_PUBLISH_SIZE_LIMIT_GB: string | undefined;
  LOADING_BAR_COLOR: string | undefined;
  SIMPLE_SITE: boolean;
  SHOW_ADS: boolean;
  KNOWN_APP_DOMAINS: string[];
  STRIPE_PUBLIC_KEY: string | undefined;
  ENABLE_UI_NOTIFICATIONS: boolean;
  ENABLE_MATURE: boolean;
  CUSTOM_HOMEPAGE: boolean;
  SHOW_TAGS_INTRO: boolean;
  LIGHTHOUSE_DEFAULT_TYPES: string | undefined;
  BRANDED_SITE: string | undefined;
  ENABLE_STRIPE: string | undefined;
  ENABLE_ARCONNECT: string | undefined;
  ENABLE_STABLECOIN: string | undefined;
  FIREBASE_API_KEY: string | undefined;
  FIREBASE_AUTH_DOMAIN: string | undefined;
  FIREBASE_PROJECT_ID: string | undefined;
  FIREBASE_STORAGE_BUCKET: string | undefined;
  FIREBASE_MESSAGING_SENDER_ID: string | undefined;
  FIREBASE_APP_ID: string | undefined;
  FIREBASE_MEASUREMENT_ID: string | undefined;
  FIREBASE_VAPID_KEY: string | undefined;
  AD_KEYWORD_BLOCKLIST: string | undefined;
  AD_KEYWORD_BLOCKLIST_CHECK_DESCRIPTION: string | undefined;
  COMMIT_ID: string | undefined;
  NODE_ENV: string | undefined;
  DYNAMIC_ROUTES_FIRST: boolean;
  SDK_API_PATH: string;
  PROXY_URL: string;
  PROXY_URL_NO_CF: string;
  URL_DEV: string;
  URL_LOCAL: string;
  FAVICON: string;
  FAVICON_NOTIFICATION: string;
}

declare const config: Config;
export = config;
