// flow-typed signature: 0be1dac32f90c556612aebfba0ccd1da
// flow-typed version: <<STUB>>/@sentry/react_v^7.8.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/react/cjs/constants' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs/errorboundary' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs/profiler' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs/reactrouter' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs/reactrouterv3' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs/reactrouterv6' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs/redux' {
  declare module.exports: any;
}

declare module '@sentry/react/cjs/sdk' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/constants' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/errorboundary' {
  declare module.exports: any;
}

declare module '@sentry/react/esm' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/profiler' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/reactrouter' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/reactrouterv3' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/reactrouterv6' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/redux' {
  declare module.exports: any;
}

declare module '@sentry/react/esm/sdk' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/react/cjs/constants.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/constants'>;
}
declare module '@sentry/react/cjs/errorboundary.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/errorboundary'>;
}
declare module '@sentry/react/cjs/index' {
  declare module.exports: $Exports<'@sentry/react/cjs'>;
}
declare module '@sentry/react/cjs/index.js' {
  declare module.exports: $Exports<'@sentry/react/cjs'>;
}
declare module '@sentry/react/cjs/profiler.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/profiler'>;
}
declare module '@sentry/react/cjs/reactrouter.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/reactrouter'>;
}
declare module '@sentry/react/cjs/reactrouterv3.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/reactrouterv3'>;
}
declare module '@sentry/react/cjs/reactrouterv6.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/reactrouterv6'>;
}
declare module '@sentry/react/cjs/redux.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/redux'>;
}
declare module '@sentry/react/cjs/sdk.js' {
  declare module.exports: $Exports<'@sentry/react/cjs/sdk'>;
}
declare module '@sentry/react/esm/constants.js' {
  declare module.exports: $Exports<'@sentry/react/esm/constants'>;
}
declare module '@sentry/react/esm/errorboundary.js' {
  declare module.exports: $Exports<'@sentry/react/esm/errorboundary'>;
}
declare module '@sentry/react/esm/index' {
  declare module.exports: $Exports<'@sentry/react/esm'>;
}
declare module '@sentry/react/esm/index.js' {
  declare module.exports: $Exports<'@sentry/react/esm'>;
}
declare module '@sentry/react/esm/profiler.js' {
  declare module.exports: $Exports<'@sentry/react/esm/profiler'>;
}
declare module '@sentry/react/esm/reactrouter.js' {
  declare module.exports: $Exports<'@sentry/react/esm/reactrouter'>;
}
declare module '@sentry/react/esm/reactrouterv3.js' {
  declare module.exports: $Exports<'@sentry/react/esm/reactrouterv3'>;
}
declare module '@sentry/react/esm/reactrouterv6.js' {
  declare module.exports: $Exports<'@sentry/react/esm/reactrouterv6'>;
}
declare module '@sentry/react/esm/redux.js' {
  declare module.exports: $Exports<'@sentry/react/esm/redux'>;
}
declare module '@sentry/react/esm/sdk.js' {
  declare module.exports: $Exports<'@sentry/react/esm/sdk'>;
}
