// flow-typed signature: 51c4329054b116f6b3d72aa81349f57d
// flow-typed version: <<STUB>>/@sentry/tracing_v^7.8.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/tracing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/tracing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/tracing/cjs/browser/backgroundtab' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/browsertracing' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/metrics' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/metrics/utils' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/request' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/router' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/types' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/getCLS' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/getFID' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/getLCP' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/bindReporter' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/generateUniqueID' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/getActivationStart' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/getNavigationEntry' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/getVisibilityWatcher' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/initMetric' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/observe' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/browser/web-vitals/lib/onHidden' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/errors' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/hubextensions' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/idletransaction' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/apollo' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/express' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/graphql' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/mongo' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/mysql' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/postgres' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/prisma' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/integrations/node/utils/node-utils' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/span' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/spanstatus' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/transaction' {
  declare module.exports: any;
}

declare module '@sentry/tracing/cjs/utils' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/backgroundtab' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/browsertracing' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/metrics' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/metrics/utils' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/request' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/router' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/types' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/getCLS' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/getFID' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/getLCP' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/bindReporter' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/generateUniqueID' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/getActivationStart' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/getNavigationEntry' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/getVisibilityWatcher' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/initMetric' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/observe' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/browser/web-vitals/lib/onHidden' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/errors' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/hubextensions' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/idletransaction' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/apollo' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/express' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/graphql' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/mongo' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/mysql' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/postgres' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/prisma' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/integrations/node/utils/node-utils' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/span' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/spanstatus' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/transaction' {
  declare module.exports: any;
}

declare module '@sentry/tracing/esm/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/tracing/cjs/browser/backgroundtab.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/backgroundtab'>;
}
declare module '@sentry/tracing/cjs/browser/browsertracing.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/browsertracing'>;
}
declare module '@sentry/tracing/cjs/browser/metrics/index' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/metrics'>;
}
declare module '@sentry/tracing/cjs/browser/metrics/index.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/metrics'>;
}
declare module '@sentry/tracing/cjs/browser/metrics/utils.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/metrics/utils'>;
}
declare module '@sentry/tracing/cjs/browser/request.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/request'>;
}
declare module '@sentry/tracing/cjs/browser/router.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/router'>;
}
declare module '@sentry/tracing/cjs/browser/types.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/types'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/getCLS.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/getCLS'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/getFID.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/getFID'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/getLCP.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/getLCP'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/bindReporter.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/bindReporter'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/generateUniqueID.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/generateUniqueID'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/getActivationStart.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/getActivationStart'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/getNavigationEntry.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/getNavigationEntry'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/getVisibilityWatcher.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/getVisibilityWatcher'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/initMetric.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/initMetric'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/observe.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/observe'>;
}
declare module '@sentry/tracing/cjs/browser/web-vitals/lib/onHidden.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/browser/web-vitals/lib/onHidden'>;
}
declare module '@sentry/tracing/cjs/errors.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/errors'>;
}
declare module '@sentry/tracing/cjs/hubextensions.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/hubextensions'>;
}
declare module '@sentry/tracing/cjs/idletransaction.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/idletransaction'>;
}
declare module '@sentry/tracing/cjs/index' {
  declare module.exports: $Exports<'@sentry/tracing/cjs'>;
}
declare module '@sentry/tracing/cjs/index.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs'>;
}
declare module '@sentry/tracing/cjs/integrations/index' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations'>;
}
declare module '@sentry/tracing/cjs/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations'>;
}
declare module '@sentry/tracing/cjs/integrations/node/apollo.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/apollo'>;
}
declare module '@sentry/tracing/cjs/integrations/node/express.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/express'>;
}
declare module '@sentry/tracing/cjs/integrations/node/graphql.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/graphql'>;
}
declare module '@sentry/tracing/cjs/integrations/node/mongo.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/mongo'>;
}
declare module '@sentry/tracing/cjs/integrations/node/mysql.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/mysql'>;
}
declare module '@sentry/tracing/cjs/integrations/node/postgres.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/postgres'>;
}
declare module '@sentry/tracing/cjs/integrations/node/prisma.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/prisma'>;
}
declare module '@sentry/tracing/cjs/integrations/node/utils/node-utils.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/integrations/node/utils/node-utils'>;
}
declare module '@sentry/tracing/cjs/span.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/span'>;
}
declare module '@sentry/tracing/cjs/spanstatus.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/spanstatus'>;
}
declare module '@sentry/tracing/cjs/transaction.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/transaction'>;
}
declare module '@sentry/tracing/cjs/utils.js' {
  declare module.exports: $Exports<'@sentry/tracing/cjs/utils'>;
}
declare module '@sentry/tracing/esm/browser/backgroundtab.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/backgroundtab'>;
}
declare module '@sentry/tracing/esm/browser/browsertracing.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/browsertracing'>;
}
declare module '@sentry/tracing/esm/browser/metrics/index' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/metrics'>;
}
declare module '@sentry/tracing/esm/browser/metrics/index.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/metrics'>;
}
declare module '@sentry/tracing/esm/browser/metrics/utils.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/metrics/utils'>;
}
declare module '@sentry/tracing/esm/browser/request.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/request'>;
}
declare module '@sentry/tracing/esm/browser/router.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/router'>;
}
declare module '@sentry/tracing/esm/browser/types.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/types'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/getCLS.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/getCLS'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/getFID.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/getFID'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/getLCP.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/getLCP'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/bindReporter.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/bindReporter'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/generateUniqueID.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/generateUniqueID'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/getActivationStart.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/getActivationStart'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/getNavigationEntry.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/getNavigationEntry'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/getVisibilityWatcher.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/getVisibilityWatcher'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/initMetric.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/initMetric'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/observe.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/observe'>;
}
declare module '@sentry/tracing/esm/browser/web-vitals/lib/onHidden.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/browser/web-vitals/lib/onHidden'>;
}
declare module '@sentry/tracing/esm/errors.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/errors'>;
}
declare module '@sentry/tracing/esm/hubextensions.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/hubextensions'>;
}
declare module '@sentry/tracing/esm/idletransaction.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/idletransaction'>;
}
declare module '@sentry/tracing/esm/index' {
  declare module.exports: $Exports<'@sentry/tracing/esm'>;
}
declare module '@sentry/tracing/esm/index.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm'>;
}
declare module '@sentry/tracing/esm/integrations/index' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations'>;
}
declare module '@sentry/tracing/esm/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations'>;
}
declare module '@sentry/tracing/esm/integrations/node/apollo.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/apollo'>;
}
declare module '@sentry/tracing/esm/integrations/node/express.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/express'>;
}
declare module '@sentry/tracing/esm/integrations/node/graphql.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/graphql'>;
}
declare module '@sentry/tracing/esm/integrations/node/mongo.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/mongo'>;
}
declare module '@sentry/tracing/esm/integrations/node/mysql.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/mysql'>;
}
declare module '@sentry/tracing/esm/integrations/node/postgres.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/postgres'>;
}
declare module '@sentry/tracing/esm/integrations/node/prisma.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/prisma'>;
}
declare module '@sentry/tracing/esm/integrations/node/utils/node-utils.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/integrations/node/utils/node-utils'>;
}
declare module '@sentry/tracing/esm/span.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/span'>;
}
declare module '@sentry/tracing/esm/spanstatus.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/spanstatus'>;
}
declare module '@sentry/tracing/esm/transaction.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/transaction'>;
}
declare module '@sentry/tracing/esm/utils.js' {
  declare module.exports: $Exports<'@sentry/tracing/esm/utils'>;
}
