// flow-typed signature: 2e5e45bf55d1b1201978de3ec6816c5f
// flow-typed version: <<STUB>>/@sentry/webpack-plugin_v^1.18.8/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/webpack-plugin/jest.config' {
  declare module.exports: any;
}

declare module '@sentry/webpack-plugin/src/cjs' {
  declare module.exports: any;
}

declare module '@sentry/webpack-plugin/src' {
  declare module.exports: any;
}

declare module '@sentry/webpack-plugin/src/sentry-webpack.module' {
  declare module.exports: any;
}

declare module '@sentry/webpack-plugin/src/sentry.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/webpack-plugin/jest.config.js' {
  declare module.exports: $Exports<'@sentry/webpack-plugin/jest.config'>;
}
declare module '@sentry/webpack-plugin/src/cjs.js' {
  declare module.exports: $Exports<'@sentry/webpack-plugin/src/cjs'>;
}
declare module '@sentry/webpack-plugin/src/index' {
  declare module.exports: $Exports<'@sentry/webpack-plugin/src'>;
}
declare module '@sentry/webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'@sentry/webpack-plugin/src'>;
}
declare module '@sentry/webpack-plugin/src/sentry-webpack.module.js' {
  declare module.exports: $Exports<'@sentry/webpack-plugin/src/sentry-webpack.module'>;
}
declare module '@sentry/webpack-plugin/src/sentry.loader.js' {
  declare module.exports: $Exports<'@sentry/webpack-plugin/src/sentry.loader'>;
}
