// flow-typed signature: 7e7241944fba68fb8e0e54c4a4a6660c
// flow-typed version: <<STUB>>/@types/webpack-config-utils_v^2.3.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack-config-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack-config-utils' {
  declare module.exports: any;
}
