import { getLanguageName } from './languages';

// supported_browser_languages
const SUPPORTED_LANGUAGES = {
  af: getLanguageName('af'),
  ar: getLanguageName('ar'),
  bn: getLanguageName('bn'),
  ca: getLanguageName('ca'),
  cs: getLanguageName('cs'),
  da: getLanguageName('da'),
  de: getLanguageName('de'),
  en: getLanguageName('en'),
  es: getLanguageName('es'),
  fi: getLanguageName('fi'),
  fr: getLanguageName('fr'),
  gu: getLanguageName('gu'),
  hi: getLanguageName('hi'),
  hr: getLanguageName('hr'),
  hu: getLanguageName('hu'),
  id: getLanguageName('id'),
  it: getLanguageName('it'),
  ja: getLanguageName('ja'),
  jv: getLanguageName('jv'),
  kn: getLanguageName('kn'),
  ml: getLanguageName('ml'),
  mr: getLanguageName('mr'),
  ms: getLanguageName('ms'),
  nl: getLanguageName('nl'),
  no: getLanguageName('no'),
  pa: getLanguageName('pa'),
  pl: getLanguageName('pl'),
  pt: getLanguageName('pt'),
  'pt-BR': getLanguageName('pt-BR'),
  ro: getLanguageName('ro'),
  ru: getLanguageName('ru'),
  sk: getLanguageName('sk'),
  sr: getLanguageName('sr'),
  sv: getLanguageName('sv'),
  th: getLanguageName('th'),
  tl: getLanguageName('tl'),
  tr: getLanguageName('tr'),
  uk: getLanguageName('uk'),
  ur: getLanguageName('ur'),
  vi: getLanguageName('vi'),
  'zh-Hans': getLanguageName('zh-Hans'),
  'zh-Hant': getLanguageName('zh-Hant'),
};

// Properties: language code (e.g. 'ja')
// Values: name of the language in native form (e.g. '日本語')
export default SUPPORTED_LANGUAGES;
