// flow-typed signature: f7b1368a3f4656a78a9ab32f243f6ba4
// flow-typed version: <<STUB>>/babel-plugin-import-glob_v^2.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-import-glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-import-glob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-import-glob/index' {
  declare module.exports: $Exports<'babel-plugin-import-glob'>;
}
declare module 'babel-plugin-import-glob/index.js' {
  declare module.exports: $Exports<'babel-plugin-import-glob'>;
}
