// flow-typed signature: 4ab4e92ed1007729bb53024d3d55e37a
// flow-typed version: <<STUB>>/dotenv-defaults_v^5.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-defaults/config' {
  declare module.exports: any;
}

declare module 'dotenv-defaults/src' {
  declare module.exports: any;
}

declare module 'dotenv-defaults/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-defaults/config.js' {
  declare module.exports: $Exports<'dotenv-defaults/config'>;
}
declare module 'dotenv-defaults/src/index' {
  declare module.exports: $Exports<'dotenv-defaults/src'>;
}
declare module 'dotenv-defaults/src/index.js' {
  declare module.exports: $Exports<'dotenv-defaults/src'>;
}
declare module 'dotenv-defaults/src/index.test.js' {
  declare module.exports: $Exports<'dotenv-defaults/src/index.test'>;
}
