// flow-typed signature: cb629c60370b0dc480ad3ff294ce993e
// flow-typed version: <<STUB>>/emoji-dictionary_v^1.0.11/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-dictionary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-dictionary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-dictionary/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-dictionary/lib/index' {
  declare module.exports: $Exports<'emoji-dictionary/lib'>;
}
declare module 'emoji-dictionary/lib/index.js' {
  declare module.exports: $Exports<'emoji-dictionary/lib'>;
}
