// flow-typed signature: 66ee3cc27715ec71cfb6836fa7b2faef
// flow-typed version: <<STUB>>/hast-util-sanitize_v^3.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hast-util-sanitize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hast-util-sanitize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hast-util-sanitize/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hast-util-sanitize/index' {
  declare module.exports: $Exports<'hast-util-sanitize'>;
}
declare module 'hast-util-sanitize/index.js' {
  declare module.exports: $Exports<'hast-util-sanitize'>;
}
declare module 'hast-util-sanitize/lib/index' {
  declare module.exports: $Exports<'hast-util-sanitize/lib'>;
}
declare module 'hast-util-sanitize/lib/index.js' {
  declare module.exports: $Exports<'hast-util-sanitize/lib'>;
}
