// flow-typed signature: 5d643edb3cda7ad3fdc42de6e6bd9048
// flow-typed version: <<STUB>>/imagesloaded_v^4.1.4/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagesloaded'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagesloaded' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imagesloaded/gulpfile' {
  declare module.exports: any;
}

declare module 'imagesloaded/imagesloaded' {
  declare module.exports: any;
}

declare module 'imagesloaded/imagesloaded.pkgd' {
  declare module.exports: any;
}

declare module 'imagesloaded/imagesloaded.pkgd.min' {
  declare module.exports: any;
}

declare module 'imagesloaded/sandbox/progress/progress' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/append' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/background' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/basics' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/data-uri' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/jquery-fail' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/jquery-success' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/local-files' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/no-images' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/non-element' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/selector-string' {
  declare module.exports: any;
}

declare module 'imagesloaded/test/unit/single-element' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imagesloaded/gulpfile.js' {
  declare module.exports: $Exports<'imagesloaded/gulpfile'>;
}
declare module 'imagesloaded/imagesloaded.js' {
  declare module.exports: $Exports<'imagesloaded/imagesloaded'>;
}
declare module 'imagesloaded/imagesloaded.pkgd.js' {
  declare module.exports: $Exports<'imagesloaded/imagesloaded.pkgd'>;
}
declare module 'imagesloaded/imagesloaded.pkgd.min.js' {
  declare module.exports: $Exports<'imagesloaded/imagesloaded.pkgd.min'>;
}
declare module 'imagesloaded/sandbox/progress/progress.js' {
  declare module.exports: $Exports<'imagesloaded/sandbox/progress/progress'>;
}
declare module 'imagesloaded/test/unit/append.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/append'>;
}
declare module 'imagesloaded/test/unit/background.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/background'>;
}
declare module 'imagesloaded/test/unit/basics.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/basics'>;
}
declare module 'imagesloaded/test/unit/data-uri.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/data-uri'>;
}
declare module 'imagesloaded/test/unit/jquery-fail.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/jquery-fail'>;
}
declare module 'imagesloaded/test/unit/jquery-success.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/jquery-success'>;
}
declare module 'imagesloaded/test/unit/local-files.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/local-files'>;
}
declare module 'imagesloaded/test/unit/no-images.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/no-images'>;
}
declare module 'imagesloaded/test/unit/non-element.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/non-element'>;
}
declare module 'imagesloaded/test/unit/selector-string.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/selector-string'>;
}
declare module 'imagesloaded/test/unit/single-element.js' {
  declare module.exports: $Exports<'imagesloaded/test/unit/single-element'>;
}
