// flow-typed signature: 65cd63e18e878820c6b0e33f07d1de4f
// flow-typed version: <<STUB>>/immer_v10.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immer/dist/cjs/immer.cjs.development' {
  declare module.exports: any;
}

declare module 'immer/dist/cjs/immer.cjs.production' {
  declare module.exports: any;
}

declare module 'immer/dist/cjs' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.legacy-esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immer/dist/cjs/immer.cjs.development.js' {
  declare module.exports: $Exports<'immer/dist/cjs/immer.cjs.development'>;
}
declare module 'immer/dist/cjs/immer.cjs.production.js' {
  declare module.exports: $Exports<'immer/dist/cjs/immer.cjs.production'>;
}
declare module 'immer/dist/cjs/index' {
  declare module.exports: $Exports<'immer/dist/cjs'>;
}
declare module 'immer/dist/cjs/index.js' {
  declare module.exports: $Exports<'immer/dist/cjs'>;
}
declare module 'immer/dist/immer.legacy-esm.js' {
  declare module.exports: $Exports<'immer/dist/immer.legacy-esm'>;
}
