// flow-typed signature: c5b09fd7b9c42b536f2d6920d8de6948
// flow-typed version: <<STUB>>/player.js_v^0.1.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'player.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'player.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'player.js/dist/player-0.1.0' {
  declare module.exports: any;
}

declare module 'player.js/dist/player-0.1.0.min' {
  declare module.exports: any;
}

declare module 'player.js/Gruntfile' {
  declare module.exports: any;
}

declare module 'player.js/src/adapters/html' {
  declare module.exports: any;
}

declare module 'player.js/src/adapters/jwplayer' {
  declare module.exports: any;
}

declare module 'player.js/src/adapters/mock' {
  declare module.exports: any;
}

declare module 'player.js/src/adapters/video' {
  declare module.exports: any;
}

declare module 'player.js/src/core' {
  declare module.exports: any;
}

declare module 'player.js/src/intro' {
  declare module.exports: any;
}

declare module 'player.js/src/keeper' {
  declare module.exports: any;
}

declare module 'player.js/src/outro' {
  declare module.exports: any;
}

declare module 'player.js/src/player' {
  declare module.exports: any;
}

declare module 'player.js/src/receiver' {
  declare module.exports: any;
}

declare module 'player.js/test/lib/qunit-1.12.0' {
  declare module.exports: any;
}

declare module 'player.js/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'player.js/dist/player-0.1.0.js' {
  declare module.exports: $Exports<'player.js/dist/player-0.1.0'>;
}
declare module 'player.js/dist/player-0.1.0.min.js' {
  declare module.exports: $Exports<'player.js/dist/player-0.1.0.min'>;
}
declare module 'player.js/Gruntfile.js' {
  declare module.exports: $Exports<'player.js/Gruntfile'>;
}
declare module 'player.js/src/adapters/html.js' {
  declare module.exports: $Exports<'player.js/src/adapters/html'>;
}
declare module 'player.js/src/adapters/jwplayer.js' {
  declare module.exports: $Exports<'player.js/src/adapters/jwplayer'>;
}
declare module 'player.js/src/adapters/mock.js' {
  declare module.exports: $Exports<'player.js/src/adapters/mock'>;
}
declare module 'player.js/src/adapters/video.js' {
  declare module.exports: $Exports<'player.js/src/adapters/video'>;
}
declare module 'player.js/src/core.js' {
  declare module.exports: $Exports<'player.js/src/core'>;
}
declare module 'player.js/src/intro.js' {
  declare module.exports: $Exports<'player.js/src/intro'>;
}
declare module 'player.js/src/keeper.js' {
  declare module.exports: $Exports<'player.js/src/keeper'>;
}
declare module 'player.js/src/outro.js' {
  declare module.exports: $Exports<'player.js/src/outro'>;
}
declare module 'player.js/src/player.js' {
  declare module.exports: $Exports<'player.js/src/player'>;
}
declare module 'player.js/src/receiver.js' {
  declare module.exports: $Exports<'player.js/src/receiver'>;
}
declare module 'player.js/test/lib/qunit-1.12.0.js' {
  declare module.exports: $Exports<'player.js/test/lib/qunit-1.12.0'>;
}
declare module 'player.js/test/test.js' {
  declare module.exports: $Exports<'player.js/test/test'>;
}
