// flow-typed signature: ed744a5b95539ef46af34926664bf479
// flow-typed version: <<STUB>>/postcss-rtl_v^2.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-rtl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-rtl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-rtl/lib/affected-props' {
  declare module.exports: any;
}

declare module 'postcss-rtl/lib/decls' {
  declare module.exports: any;
}

declare module 'postcss-rtl/lib' {
  declare module.exports: any;
}

declare module 'postcss-rtl/lib/keyframes' {
  declare module.exports: any;
}

declare module 'postcss-rtl/lib/options' {
  declare module.exports: any;
}

declare module 'postcss-rtl/lib/prefixes-config' {
  declare module.exports: any;
}

declare module 'postcss-rtl/lib/rules' {
  declare module.exports: any;
}

declare module 'postcss-rtl/lib/selectors' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/__tests__/cases.spec' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/affected-props' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/decls' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/keyframes' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/options' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/prefixes-config' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/rules' {
  declare module.exports: any;
}

declare module 'postcss-rtl/src/selectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-rtl/lib/affected-props.js' {
  declare module.exports: $Exports<'postcss-rtl/lib/affected-props'>;
}
declare module 'postcss-rtl/lib/decls.js' {
  declare module.exports: $Exports<'postcss-rtl/lib/decls'>;
}
declare module 'postcss-rtl/lib/index' {
  declare module.exports: $Exports<'postcss-rtl/lib'>;
}
declare module 'postcss-rtl/lib/index.js' {
  declare module.exports: $Exports<'postcss-rtl/lib'>;
}
declare module 'postcss-rtl/lib/keyframes.js' {
  declare module.exports: $Exports<'postcss-rtl/lib/keyframes'>;
}
declare module 'postcss-rtl/lib/options.js' {
  declare module.exports: $Exports<'postcss-rtl/lib/options'>;
}
declare module 'postcss-rtl/lib/prefixes-config.js' {
  declare module.exports: $Exports<'postcss-rtl/lib/prefixes-config'>;
}
declare module 'postcss-rtl/lib/rules.js' {
  declare module.exports: $Exports<'postcss-rtl/lib/rules'>;
}
declare module 'postcss-rtl/lib/selectors.js' {
  declare module.exports: $Exports<'postcss-rtl/lib/selectors'>;
}
declare module 'postcss-rtl/src/__tests__/cases.spec.js' {
  declare module.exports: $Exports<'postcss-rtl/src/__tests__/cases.spec'>;
}
declare module 'postcss-rtl/src/affected-props.js' {
  declare module.exports: $Exports<'postcss-rtl/src/affected-props'>;
}
declare module 'postcss-rtl/src/decls.js' {
  declare module.exports: $Exports<'postcss-rtl/src/decls'>;
}
declare module 'postcss-rtl/src/index' {
  declare module.exports: $Exports<'postcss-rtl/src'>;
}
declare module 'postcss-rtl/src/index.js' {
  declare module.exports: $Exports<'postcss-rtl/src'>;
}
declare module 'postcss-rtl/src/keyframes.js' {
  declare module.exports: $Exports<'postcss-rtl/src/keyframes'>;
}
declare module 'postcss-rtl/src/options.js' {
  declare module.exports: $Exports<'postcss-rtl/src/options'>;
}
declare module 'postcss-rtl/src/prefixes-config.js' {
  declare module.exports: $Exports<'postcss-rtl/src/prefixes-config'>;
}
declare module 'postcss-rtl/src/rules.js' {
  declare module.exports: $Exports<'postcss-rtl/src/rules'>;
}
declare module 'postcss-rtl/src/selectors.js' {
  declare module.exports: $Exports<'postcss-rtl/src/selectors'>;
}
