// flow-typed signature: 3ae4c6fabd93b80eedc0a733b962e18c
// flow-typed version: <<STUB>>/re-reselect_v^4.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-reselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 're-reselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-reselect/dist' {
  declare module.exports: any;
}

declare module 're-reselect/es' {
  declare module.exports: any;
}

declare module 're-reselect/lib' {
  declare module.exports: any;
}

declare module 're-reselect/src/__tests__/createCachedSelector.test' {
  declare module.exports: any;
}

declare module 're-reselect/src/__tests__/createStructuredCachedSelector.test' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__tests__/FifoMapCache.spec' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__tests__/FifoObjectCache.spec' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__tests__/FlatMapCache.spec' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__tests__/FlatObjectCache.spec' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__tests__/LruMapCache.spec' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__tests__/LruObjectCache.spec' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__util__/fillCacheWith' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__util__/testBasicBehavior' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__util__/testCacheSizeOptionValidation' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__util__/testFifoBehavior' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__util__/testLruBehavior' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__util__/testMapCacheKeyBehavior' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/__util__/testObjectCacheKeyBehavior' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FifoMapCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FifoObjectCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FlatMapCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/FlatObjectCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/LruMapCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/LruObjectCache' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/util/isStringOrNumber' {
  declare module.exports: any;
}

declare module 're-reselect/src/cache/util/validateCacheSize' {
  declare module.exports: any;
}

declare module 're-reselect/src/createCachedSelector' {
  declare module.exports: any;
}

declare module 're-reselect/src/createStructuredCachedSelector' {
  declare module.exports: any;
}

declare module 're-reselect/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-reselect/dist/index' {
  declare module.exports: $Exports<'re-reselect/dist'>;
}
declare module 're-reselect/dist/index.js' {
  declare module.exports: $Exports<'re-reselect/dist'>;
}
declare module 're-reselect/es/index' {
  declare module.exports: $Exports<'re-reselect/es'>;
}
declare module 're-reselect/es/index.js' {
  declare module.exports: $Exports<'re-reselect/es'>;
}
declare module 're-reselect/lib/index' {
  declare module.exports: $Exports<'re-reselect/lib'>;
}
declare module 're-reselect/lib/index.js' {
  declare module.exports: $Exports<'re-reselect/lib'>;
}
declare module 're-reselect/src/__tests__/createCachedSelector.test.js' {
  declare module.exports: $Exports<'re-reselect/src/__tests__/createCachedSelector.test'>;
}
declare module 're-reselect/src/__tests__/createStructuredCachedSelector.test.js' {
  declare module.exports: $Exports<'re-reselect/src/__tests__/createStructuredCachedSelector.test'>;
}
declare module 're-reselect/src/cache/__tests__/FifoMapCache.spec.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__tests__/FifoMapCache.spec'>;
}
declare module 're-reselect/src/cache/__tests__/FifoObjectCache.spec.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__tests__/FifoObjectCache.spec'>;
}
declare module 're-reselect/src/cache/__tests__/FlatMapCache.spec.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__tests__/FlatMapCache.spec'>;
}
declare module 're-reselect/src/cache/__tests__/FlatObjectCache.spec.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__tests__/FlatObjectCache.spec'>;
}
declare module 're-reselect/src/cache/__tests__/LruMapCache.spec.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__tests__/LruMapCache.spec'>;
}
declare module 're-reselect/src/cache/__tests__/LruObjectCache.spec.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__tests__/LruObjectCache.spec'>;
}
declare module 're-reselect/src/cache/__util__/fillCacheWith.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__util__/fillCacheWith'>;
}
declare module 're-reselect/src/cache/__util__/testBasicBehavior.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__util__/testBasicBehavior'>;
}
declare module 're-reselect/src/cache/__util__/testCacheSizeOptionValidation.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__util__/testCacheSizeOptionValidation'>;
}
declare module 're-reselect/src/cache/__util__/testFifoBehavior.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__util__/testFifoBehavior'>;
}
declare module 're-reselect/src/cache/__util__/testLruBehavior.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__util__/testLruBehavior'>;
}
declare module 're-reselect/src/cache/__util__/testMapCacheKeyBehavior.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__util__/testMapCacheKeyBehavior'>;
}
declare module 're-reselect/src/cache/__util__/testObjectCacheKeyBehavior.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/__util__/testObjectCacheKeyBehavior'>;
}
declare module 're-reselect/src/cache/FifoMapCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FifoMapCache'>;
}
declare module 're-reselect/src/cache/FifoObjectCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FifoObjectCache'>;
}
declare module 're-reselect/src/cache/FlatMapCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FlatMapCache'>;
}
declare module 're-reselect/src/cache/FlatObjectCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/FlatObjectCache'>;
}
declare module 're-reselect/src/cache/LruMapCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/LruMapCache'>;
}
declare module 're-reselect/src/cache/LruObjectCache.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/LruObjectCache'>;
}
declare module 're-reselect/src/cache/util/isStringOrNumber.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/util/isStringOrNumber'>;
}
declare module 're-reselect/src/cache/util/validateCacheSize.js' {
  declare module.exports: $Exports<'re-reselect/src/cache/util/validateCacheSize'>;
}
declare module 're-reselect/src/createCachedSelector.js' {
  declare module.exports: $Exports<'re-reselect/src/createCachedSelector'>;
}
declare module 're-reselect/src/createStructuredCachedSelector.js' {
  declare module.exports: $Exports<'re-reselect/src/createStructuredCachedSelector'>;
}
declare module 're-reselect/src/index' {
  declare module.exports: $Exports<'re-reselect/src'>;
}
declare module 're-reselect/src/index.js' {
  declare module.exports: $Exports<'re-reselect/src'>;
}
