// flow-typed signature: b1a4378503c5a49fa80dd46f1fdee2d9
// flow-typed version: <<STUB>>/react-datetime-picker_v^3.4.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datetime-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datetime-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-datetime-picker/dist/DateTimeInput' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/DateTimeInput/NativeInput' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/DateTimePicker' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/Divider' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/entry' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/entry.nostyle' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/shared/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/shared/dates' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/dist/shared/utils' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/DateTimeInput' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/DateTimeInput.spec' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/DateTimeInput/NativeInput' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/DateTimeInput/NativeInput.spec' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/DateTimePicker' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/DateTimePicker.spec' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/Divider' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/entry' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/entry.nostyle' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/shared/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/shared/dateFormatter.spec' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/shared/dates' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/shared/dates.spec' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/shared/utils' {
  declare module.exports: any;
}

declare module 'react-datetime-picker/src/shared/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-datetime-picker/dist/DateTimeInput.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/DateTimeInput'>;
}
declare module 'react-datetime-picker/dist/DateTimeInput/NativeInput.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/DateTimeInput/NativeInput'>;
}
declare module 'react-datetime-picker/dist/DateTimePicker.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/DateTimePicker'>;
}
declare module 'react-datetime-picker/dist/Divider.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/Divider'>;
}
declare module 'react-datetime-picker/dist/entry.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/entry'>;
}
declare module 'react-datetime-picker/dist/entry.nostyle.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/entry.nostyle'>;
}
declare module 'react-datetime-picker/dist/shared/dateFormatter.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/shared/dateFormatter'>;
}
declare module 'react-datetime-picker/dist/shared/dates.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/shared/dates'>;
}
declare module 'react-datetime-picker/dist/shared/propTypes.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/shared/propTypes'>;
}
declare module 'react-datetime-picker/dist/shared/utils.js' {
  declare module.exports: $Exports<'react-datetime-picker/dist/shared/utils'>;
}
declare module 'react-datetime-picker/src/DateTimeInput.jsx' {
  declare module.exports: $Exports<'react-datetime-picker/src/DateTimeInput'>;
}
declare module 'react-datetime-picker/src/DateTimeInput.spec.jsx' {
  declare module.exports: $Exports<'react-datetime-picker/src/DateTimeInput.spec'>;
}
declare module 'react-datetime-picker/src/DateTimeInput/NativeInput.jsx' {
  declare module.exports: $Exports<'react-datetime-picker/src/DateTimeInput/NativeInput'>;
}
declare module 'react-datetime-picker/src/DateTimeInput/NativeInput.spec.jsx' {
  declare module.exports: $Exports<'react-datetime-picker/src/DateTimeInput/NativeInput.spec'>;
}
declare module 'react-datetime-picker/src/DateTimePicker.jsx' {
  declare module.exports: $Exports<'react-datetime-picker/src/DateTimePicker'>;
}
declare module 'react-datetime-picker/src/DateTimePicker.spec.jsx' {
  declare module.exports: $Exports<'react-datetime-picker/src/DateTimePicker.spec'>;
}
declare module 'react-datetime-picker/src/Divider.jsx' {
  declare module.exports: $Exports<'react-datetime-picker/src/Divider'>;
}
declare module 'react-datetime-picker/src/entry.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/entry'>;
}
declare module 'react-datetime-picker/src/entry.nostyle.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/entry.nostyle'>;
}
declare module 'react-datetime-picker/src/shared/dateFormatter.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/shared/dateFormatter'>;
}
declare module 'react-datetime-picker/src/shared/dateFormatter.spec.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/shared/dateFormatter.spec'>;
}
declare module 'react-datetime-picker/src/shared/dates.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/shared/dates'>;
}
declare module 'react-datetime-picker/src/shared/dates.spec.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/shared/dates.spec'>;
}
declare module 'react-datetime-picker/src/shared/propTypes.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/shared/propTypes'>;
}
declare module 'react-datetime-picker/src/shared/utils.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/shared/utils'>;
}
declare module 'react-datetime-picker/src/shared/utils.spec.js' {
  declare module.exports: $Exports<'react-datetime-picker/src/shared/utils.spec'>;
}
