// flow-typed signature: 0cba593f75a59c1bb428e6f00a3e9d78
// flow-typed version: <<STUB>>/react-top-loading-bar_v^2.0.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-top-loading-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-top-loading-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-top-loading-bar/dist' {
  declare module.exports: any;
}

declare module 'react-top-loading-bar/dist/index.modern' {
  declare module.exports: any;
}

declare module 'react-top-loading-bar/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-top-loading-bar/dist/index' {
  declare module.exports: $Exports<'react-top-loading-bar/dist'>;
}
declare module 'react-top-loading-bar/dist/index.js' {
  declare module.exports: $Exports<'react-top-loading-bar/dist'>;
}
declare module 'react-top-loading-bar/dist/index.modern.js' {
  declare module.exports: $Exports<'react-top-loading-bar/dist/index.modern'>;
}
declare module 'react-top-loading-bar/dist/index.umd.js' {
  declare module.exports: $Exports<'react-top-loading-bar/dist/index.umd'>;
}
