// flow-typed signature: 83ae66a78ce93e65dbee4854096e7248
// flow-typed version: <<STUB>>/react-google-recaptcha_v^2.0.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-recaptcha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-recaptcha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-recaptcha/jest.config' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/esm' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/esm/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/esm/recaptcha' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/recaptcha' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src/recaptcha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-recaptcha/jest.config.js' {
  declare module.exports: $Exports<'react-google-recaptcha/jest.config'>;
}
declare module 'react-google-recaptcha/lib/esm/index' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/esm'>;
}
declare module 'react-google-recaptcha/lib/esm/index.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/esm'>;
}
declare module 'react-google-recaptcha/lib/esm/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/esm/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/lib/esm/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/esm/recaptcha'>;
}
declare module 'react-google-recaptcha/lib/index' {
  declare module.exports: $Exports<'react-google-recaptcha/lib'>;
}
declare module 'react-google-recaptcha/lib/index.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib'>;
}
declare module 'react-google-recaptcha/lib/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/lib/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/recaptcha'>;
}
declare module 'react-google-recaptcha/src/index' {
  declare module.exports: $Exports<'react-google-recaptcha/src'>;
}
declare module 'react-google-recaptcha/src/index.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src'>;
}
declare module 'react-google-recaptcha/src/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/src/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src/recaptcha'>;
}
