// flow-typed signature: 494a4945c4e46ccbd4d835c7e2eaa656
// flow-typed version: <<STUB>>/redux-persist-transform-filter_v0.0.16/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-transform-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-transform-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-transform-filter/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-transform-filter/dist/index' {
  declare module.exports: $Exports<'redux-persist-transform-filter/dist'>;
}
declare module 'redux-persist-transform-filter/dist/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-filter/dist'>;
}
declare module 'redux-persist-transform-filter/index' {
  declare module.exports: $Exports<'redux-persist-transform-filter'>;
}
declare module 'redux-persist-transform-filter/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-filter'>;
}
