// flow-typed signature: dea9d5fd2c5aab2e74580e1c6fe36857
// flow-typed version: <<STUB>>/redux-persist-transform-compress_v^4.2.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-transform-compress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-transform-compress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-transform-compress/lib' {
  declare module.exports: any;
}

declare module 'redux-persist-transform-compress/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-transform-compress/lib/index' {
  declare module.exports: $Exports<'redux-persist-transform-compress/lib'>;
}
declare module 'redux-persist-transform-compress/lib/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-compress/lib'>;
}
declare module 'redux-persist-transform-compress/src/index' {
  declare module.exports: $Exports<'redux-persist-transform-compress/src'>;
}
declare module 'redux-persist-transform-compress/src/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-compress/src'>;
}
