// flow-typed signature: 63befcc5ca8974044958c6288d01b95f
// flow-typed version: <<STUB>>/redux-state-sync_v^3.1.4/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-state-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-state-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-state-sync/__mocks__/envMock' {
  declare module.exports: any;
}

declare module 'redux-state-sync/__test__/syncStorage.test' {
  declare module.exports: any;
}

declare module 'redux-state-sync/dist/syncState' {
  declare module.exports: any;
}

declare module 'redux-state-sync/dist/syncState.umd' {
  declare module.exports: any;
}

declare module 'redux-state-sync/dist/syncState.umd.min' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/actions' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/components/App' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/components/Footer' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/components/Link' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/components/Todo' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/components/TodoList' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/containers/AddTodo' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/containers/FilterLink' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/containers/VisibleTodoList' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/lib/syncState' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/reducers' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/reducers/todo' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/reducers/todos' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/reducers/visibilityFilter' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example_immutable/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/actions' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/components/App' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/components/Footer' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/components/Link' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/components/Todo' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/components/TodoList' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/containers/AddTodo' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/containers/FilterLink' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/containers/VisibleTodoList' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/lib/syncState' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/reducers' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/reducers/todo' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/reducers/todos' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/reducers/visibilityFilter' {
  declare module.exports: any;
}

declare module 'redux-state-sync/example/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module 'redux-state-sync/src/syncState' {
  declare module.exports: any;
}

declare module 'redux-state-sync/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-state-sync/__mocks__/envMock.js' {
  declare module.exports: $Exports<'redux-state-sync/__mocks__/envMock'>;
}
declare module 'redux-state-sync/__test__/syncStorage.test.js' {
  declare module.exports: $Exports<'redux-state-sync/__test__/syncStorage.test'>;
}
declare module 'redux-state-sync/dist/syncState.js' {
  declare module.exports: $Exports<'redux-state-sync/dist/syncState'>;
}
declare module 'redux-state-sync/dist/syncState.umd.js' {
  declare module.exports: $Exports<'redux-state-sync/dist/syncState.umd'>;
}
declare module 'redux-state-sync/dist/syncState.umd.min.js' {
  declare module.exports: $Exports<'redux-state-sync/dist/syncState.umd.min'>;
}
declare module 'redux-state-sync/example_immutable/src/actions/index' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/actions'>;
}
declare module 'redux-state-sync/example_immutable/src/actions/index.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/actions'>;
}
declare module 'redux-state-sync/example_immutable/src/components/App.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/components/App'>;
}
declare module 'redux-state-sync/example_immutable/src/components/Footer.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/components/Footer'>;
}
declare module 'redux-state-sync/example_immutable/src/components/Link.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/components/Link'>;
}
declare module 'redux-state-sync/example_immutable/src/components/Todo.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/components/Todo'>;
}
declare module 'redux-state-sync/example_immutable/src/components/TodoList.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/components/TodoList'>;
}
declare module 'redux-state-sync/example_immutable/src/containers/AddTodo.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/containers/AddTodo'>;
}
declare module 'redux-state-sync/example_immutable/src/containers/FilterLink.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/containers/FilterLink'>;
}
declare module 'redux-state-sync/example_immutable/src/containers/VisibleTodoList.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/containers/VisibleTodoList'>;
}
declare module 'redux-state-sync/example_immutable/src/index' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src'>;
}
declare module 'redux-state-sync/example_immutable/src/index.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src'>;
}
declare module 'redux-state-sync/example_immutable/src/lib/syncState.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/lib/syncState'>;
}
declare module 'redux-state-sync/example_immutable/src/reducers/index' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/reducers'>;
}
declare module 'redux-state-sync/example_immutable/src/reducers/index.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/reducers'>;
}
declare module 'redux-state-sync/example_immutable/src/reducers/todo.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/reducers/todo'>;
}
declare module 'redux-state-sync/example_immutable/src/reducers/todos.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/reducers/todos'>;
}
declare module 'redux-state-sync/example_immutable/src/reducers/visibilityFilter.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/reducers/visibilityFilter'>;
}
declare module 'redux-state-sync/example_immutable/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'redux-state-sync/example_immutable/src/registerServiceWorker'>;
}
declare module 'redux-state-sync/example/src/actions/index' {
  declare module.exports: $Exports<'redux-state-sync/example/src/actions'>;
}
declare module 'redux-state-sync/example/src/actions/index.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/actions'>;
}
declare module 'redux-state-sync/example/src/components/App.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/components/App'>;
}
declare module 'redux-state-sync/example/src/components/Footer.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/components/Footer'>;
}
declare module 'redux-state-sync/example/src/components/Link.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/components/Link'>;
}
declare module 'redux-state-sync/example/src/components/Todo.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/components/Todo'>;
}
declare module 'redux-state-sync/example/src/components/TodoList.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/components/TodoList'>;
}
declare module 'redux-state-sync/example/src/containers/AddTodo.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/containers/AddTodo'>;
}
declare module 'redux-state-sync/example/src/containers/FilterLink.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/containers/FilterLink'>;
}
declare module 'redux-state-sync/example/src/containers/VisibleTodoList.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/containers/VisibleTodoList'>;
}
declare module 'redux-state-sync/example/src/index' {
  declare module.exports: $Exports<'redux-state-sync/example/src'>;
}
declare module 'redux-state-sync/example/src/index.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src'>;
}
declare module 'redux-state-sync/example/src/lib/syncState.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/lib/syncState'>;
}
declare module 'redux-state-sync/example/src/reducers/index' {
  declare module.exports: $Exports<'redux-state-sync/example/src/reducers'>;
}
declare module 'redux-state-sync/example/src/reducers/index.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/reducers'>;
}
declare module 'redux-state-sync/example/src/reducers/todo.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/reducers/todo'>;
}
declare module 'redux-state-sync/example/src/reducers/todos.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/reducers/todos'>;
}
declare module 'redux-state-sync/example/src/reducers/visibilityFilter.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/reducers/visibilityFilter'>;
}
declare module 'redux-state-sync/example/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'redux-state-sync/example/src/registerServiceWorker'>;
}
declare module 'redux-state-sync/src/syncState.js' {
  declare module.exports: $Exports<'redux-state-sync/src/syncState'>;
}
declare module 'redux-state-sync/webpack.config.babel.js' {
  declare module.exports: $Exports<'redux-state-sync/webpack.config.babel'>;
}
