// flow-typed signature: f08b72be970eb3d9b3946048cc73958b
// flow-typed version: <<STUB>>/remark-attr_v^0.8.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-attr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-attr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-attr/__tests__' {
  declare module.exports: any;
}

declare module 'remark-attr/dist/dom-event-handler' {
  declare module.exports: any;
}

declare module 'remark-attr/dist' {
  declare module.exports: any;
}

declare module 'remark-attr/src/dom-event-handler' {
  declare module.exports: any;
}

declare module 'remark-attr/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-attr/__tests__/index' {
  declare module.exports: $Exports<'remark-attr/__tests__'>;
}
declare module 'remark-attr/__tests__/index.js' {
  declare module.exports: $Exports<'remark-attr/__tests__'>;
}
declare module 'remark-attr/dist/dom-event-handler.js' {
  declare module.exports: $Exports<'remark-attr/dist/dom-event-handler'>;
}
declare module 'remark-attr/dist/index' {
  declare module.exports: $Exports<'remark-attr/dist'>;
}
declare module 'remark-attr/dist/index.js' {
  declare module.exports: $Exports<'remark-attr/dist'>;
}
declare module 'remark-attr/src/dom-event-handler.js' {
  declare module.exports: $Exports<'remark-attr/src/dom-event-handler'>;
}
declare module 'remark-attr/src/index' {
  declare module.exports: $Exports<'remark-attr/src'>;
}
declare module 'remark-attr/src/index.js' {
  declare module.exports: $Exports<'remark-attr/src'>;
}
