// flow-typed signature: db11cd14795cb42066ec71621c667d1f
// flow-typed version: <<STUB>>/remark-emoji_v^2.0.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-emoji/index' {
  declare module.exports: $Exports<'remark-emoji'>;
}
declare module 'remark-emoji/index.js' {
  declare module.exports: $Exports<'remark-emoji'>;
}
