// flow-typed signature: 93b64ad77026a3582b53e61dc7815553
// flow-typed version: <<STUB>>/remove-markdown_v^0.3.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remove-markdown/test/remove-markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remove-markdown/index' {
  declare module.exports: $Exports<'remove-markdown'>;
}
declare module 'remove-markdown/index.js' {
  declare module.exports: $Exports<'remove-markdown'>;
}
declare module 'remove-markdown/test/remove-markdown.js' {
  declare module.exports: $Exports<'remove-markdown/test/remove-markdown'>;
}
