// flow-typed signature: 91c56bb334e590fa9aabcf59cdd77d72
// flow-typed version: <<STUB>>/rss_v^1.2.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rss/Gruntfile' {
  declare module.exports: any;
}

declare module 'rss/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rss/Gruntfile.js' {
  declare module.exports: $Exports<'rss/Gruntfile'>;
}
declare module 'rss/lib/index' {
  declare module.exports: $Exports<'rss/lib'>;
}
declare module 'rss/lib/index.js' {
  declare module.exports: $Exports<'rss/lib'>;
}
