// flow-typed signature: 364b153f9284c6a0208d2c938794e77f
// flow-typed version: <<STUB>>/sass-loader_v^13.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'sass-loader/dist' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/SassError' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/SassWarning' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-loader/dist/cjs.js' {
  declare module.exports: $Exports<'sass-loader/dist/cjs'>;
}
declare module 'sass-loader/dist/index' {
  declare module.exports: $Exports<'sass-loader/dist'>;
}
declare module 'sass-loader/dist/index.js' {
  declare module.exports: $Exports<'sass-loader/dist'>;
}
declare module 'sass-loader/dist/SassError.js' {
  declare module.exports: $Exports<'sass-loader/dist/SassError'>;
}
declare module 'sass-loader/dist/SassWarning.js' {
  declare module.exports: $Exports<'sass-loader/dist/SassWarning'>;
}
declare module 'sass-loader/dist/utils.js' {
  declare module.exports: $Exports<'sass-loader/dist/utils'>;
}
