// flow-typed signature: e9b8f33f4f36b33b6309724fb821913e
// flow-typed version: <<STUB>>/style-loader_v^3.3.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'style-loader/dist' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/injectStylesIntoLinkTag' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/injectStylesIntoStyleTag' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/insertBySelector' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/insertStyleElement' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/isEqualLocals' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/isOldIE' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/setAttributesWithAttributes' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/setAttributesWithAttributesAndNonce' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/setAttributesWithoutAttributes' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/singletonStyleDomAPI' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/styleDomAPI' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/styleTagTransform' {
  declare module.exports: any;
}

declare module 'style-loader/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-loader/dist/cjs.js' {
  declare module.exports: $Exports<'style-loader/dist/cjs'>;
}
declare module 'style-loader/dist/index' {
  declare module.exports: $Exports<'style-loader/dist'>;
}
declare module 'style-loader/dist/index.js' {
  declare module.exports: $Exports<'style-loader/dist'>;
}
declare module 'style-loader/dist/runtime/injectStylesIntoLinkTag.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/injectStylesIntoLinkTag'>;
}
declare module 'style-loader/dist/runtime/injectStylesIntoStyleTag.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/injectStylesIntoStyleTag'>;
}
declare module 'style-loader/dist/runtime/insertBySelector.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/insertBySelector'>;
}
declare module 'style-loader/dist/runtime/insertStyleElement.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/insertStyleElement'>;
}
declare module 'style-loader/dist/runtime/isEqualLocals.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/isEqualLocals'>;
}
declare module 'style-loader/dist/runtime/isOldIE.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/isOldIE'>;
}
declare module 'style-loader/dist/runtime/setAttributesWithAttributes.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/setAttributesWithAttributes'>;
}
declare module 'style-loader/dist/runtime/setAttributesWithAttributesAndNonce.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/setAttributesWithAttributesAndNonce'>;
}
declare module 'style-loader/dist/runtime/setAttributesWithoutAttributes.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/setAttributesWithoutAttributes'>;
}
declare module 'style-loader/dist/runtime/singletonStyleDomAPI.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/singletonStyleDomAPI'>;
}
declare module 'style-loader/dist/runtime/styleDomAPI.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/styleDomAPI'>;
}
declare module 'style-loader/dist/runtime/styleTagTransform.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/styleTagTransform'>;
}
declare module 'style-loader/dist/utils.js' {
  declare module.exports: $Exports<'style-loader/dist/utils'>;
}
