// flow-typed signature: c28861233005181bc4ae07d043c8cce4
// flow-typed version: <<STUB>>/terser-webpack-plugin_v^5.3.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terser-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terser-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terser-webpack-plugin/dist' {
  declare module.exports: any;
}

declare module 'terser-webpack-plugin/dist/minify' {
  declare module.exports: any;
}

declare module 'terser-webpack-plugin/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terser-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist'>;
}
declare module 'terser-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist'>;
}
declare module 'terser-webpack-plugin/dist/minify.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist/minify'>;
}
declare module 'terser-webpack-plugin/dist/utils.js' {
  declare module.exports: $Exports<'terser-webpack-plugin/dist/utils'>;
}
