// flow-typed signature: cd36e8ff2450fe15e07dafa449267899
// flow-typed version: <<STUB>>/tus-js-client_v^2.3.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tus-js-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tus-js-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tus-js-client/bin/browserstack-jasmine' {
  declare module.exports: any;
}

declare module 'tus-js-client/bin/puppeteer-jasmine' {
  declare module.exports: any;
}

declare module 'tus-js-client/demos/browser/demo' {
  declare module.exports: any;
}

declare module 'tus-js-client/demos/browser/video' {
  declare module.exports: any;
}

declare module 'tus-js-client/demos/cordova/hooks/before_prepare/copy_tus_files' {
  declare module.exports: any;
}

declare module 'tus-js-client/demos/cordova/www/js' {
  declare module.exports: any;
}

declare module 'tus-js-client/demos/nodejs' {
  declare module.exports: any;
}

declare module 'tus-js-client/demos/reactnative/App' {
  declare module.exports: any;
}

declare module 'tus-js-client/demos/reactnative/babel.config' {
  declare module.exports: any;
}

declare module 'tus-js-client/dist/browser-test-bundle' {
  declare module.exports: any;
}

declare module 'tus-js-client/dist/tus' {
  declare module.exports: any;
}

declare module 'tus-js-client/dist/tus.min' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/fileReader' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/fingerprint' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/httpStack' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/isCordova' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/isReactNative' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/readAsByteArray' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/request' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/source' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/sources/FileSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/sources/isCordova' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/sources/readAsByteArray' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/sources/StreamSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/storage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/uriToBlob' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/browser/urlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/error' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/logger' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/fileReader' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/fingerprint' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/httpStack' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/isReactNative' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/request' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/source' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/sources/BufferSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/sources/FileSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/sources/SlicingStream' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/sources/StreamSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/storage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/node/urlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/noopUrlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/upload' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/urlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.es5/uuid' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/fileReader' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/fingerprint' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/httpStack' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/isCordova' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/isReactNative' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/readAsByteArray' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/sources/FileSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/sources/isCordova' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/sources/readAsByteArray' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/sources/StreamSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/uriToBlob' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/browser/urlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/error' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/logger' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/fileReader' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/fingerprint' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/httpStack' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/sources/BufferSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/sources/FileSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/sources/SlicingStream' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/sources/StreamSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/node/urlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/noopUrlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/upload' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib.esm/uuid' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/fileReader' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/fingerprint' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/httpStack' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/isReactNative' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/sources/FileSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/sources/isCordova' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/sources/readAsByteArray' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/sources/StreamSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/uriToBlob' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/browser/urlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/error' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/logger' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/fileReader' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/fingerprint' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/httpStack' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/sources/BufferSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/sources/FileSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/sources/SlicingStream' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/sources/StreamSource' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/node/urlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/noopUrlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/upload' {
  declare module.exports: any;
}

declare module 'tus-js-client/lib/uuid' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/browser-index' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/helpers/assertUrlStorage' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/helpers/puppeteer/reporter' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/helpers/utils' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/node-index' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/test-browser-specific' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/test-common' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/test-end-to-end' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/test-node-specific' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/test-parallel-uploads' {
  declare module.exports: any;
}

declare module 'tus-js-client/test/spec/test-terminate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tus-js-client/bin/browserstack-jasmine.js' {
  declare module.exports: $Exports<'tus-js-client/bin/browserstack-jasmine'>;
}
declare module 'tus-js-client/bin/puppeteer-jasmine.js' {
  declare module.exports: $Exports<'tus-js-client/bin/puppeteer-jasmine'>;
}
declare module 'tus-js-client/demos/browser/demo.js' {
  declare module.exports: $Exports<'tus-js-client/demos/browser/demo'>;
}
declare module 'tus-js-client/demos/browser/video.js' {
  declare module.exports: $Exports<'tus-js-client/demos/browser/video'>;
}
declare module 'tus-js-client/demos/cordova/hooks/before_prepare/copy_tus_files.js' {
  declare module.exports: $Exports<'tus-js-client/demos/cordova/hooks/before_prepare/copy_tus_files'>;
}
declare module 'tus-js-client/demos/cordova/www/js/index' {
  declare module.exports: $Exports<'tus-js-client/demos/cordova/www/js'>;
}
declare module 'tus-js-client/demos/cordova/www/js/index.js' {
  declare module.exports: $Exports<'tus-js-client/demos/cordova/www/js'>;
}
declare module 'tus-js-client/demos/nodejs/index' {
  declare module.exports: $Exports<'tus-js-client/demos/nodejs'>;
}
declare module 'tus-js-client/demos/nodejs/index.js' {
  declare module.exports: $Exports<'tus-js-client/demos/nodejs'>;
}
declare module 'tus-js-client/demos/reactnative/App.js' {
  declare module.exports: $Exports<'tus-js-client/demos/reactnative/App'>;
}
declare module 'tus-js-client/demos/reactnative/babel.config.js' {
  declare module.exports: $Exports<'tus-js-client/demos/reactnative/babel.config'>;
}
declare module 'tus-js-client/dist/browser-test-bundle.js' {
  declare module.exports: $Exports<'tus-js-client/dist/browser-test-bundle'>;
}
declare module 'tus-js-client/dist/tus.js' {
  declare module.exports: $Exports<'tus-js-client/dist/tus'>;
}
declare module 'tus-js-client/dist/tus.min.js' {
  declare module.exports: $Exports<'tus-js-client/dist/tus.min'>;
}
declare module 'tus-js-client/lib.es5/browser/fileReader.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/fileReader'>;
}
declare module 'tus-js-client/lib.es5/browser/fingerprint.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/fingerprint'>;
}
declare module 'tus-js-client/lib.es5/browser/httpStack.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/httpStack'>;
}
declare module 'tus-js-client/lib.es5/browser/index' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser'>;
}
declare module 'tus-js-client/lib.es5/browser/index.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser'>;
}
declare module 'tus-js-client/lib.es5/browser/isCordova.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/isCordova'>;
}
declare module 'tus-js-client/lib.es5/browser/isReactNative.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/isReactNative'>;
}
declare module 'tus-js-client/lib.es5/browser/readAsByteArray.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/readAsByteArray'>;
}
declare module 'tus-js-client/lib.es5/browser/request.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/request'>;
}
declare module 'tus-js-client/lib.es5/browser/source.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/source'>;
}
declare module 'tus-js-client/lib.es5/browser/sources/FileSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/sources/FileSource'>;
}
declare module 'tus-js-client/lib.es5/browser/sources/isCordova.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/sources/isCordova'>;
}
declare module 'tus-js-client/lib.es5/browser/sources/readAsByteArray.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/sources/readAsByteArray'>;
}
declare module 'tus-js-client/lib.es5/browser/sources/StreamSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/sources/StreamSource'>;
}
declare module 'tus-js-client/lib.es5/browser/storage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/storage'>;
}
declare module 'tus-js-client/lib.es5/browser/uriToBlob.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/uriToBlob'>;
}
declare module 'tus-js-client/lib.es5/browser/urlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/browser/urlStorage'>;
}
declare module 'tus-js-client/lib.es5/error.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/error'>;
}
declare module 'tus-js-client/lib.es5/logger.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/logger'>;
}
declare module 'tus-js-client/lib.es5/node/fileReader.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/fileReader'>;
}
declare module 'tus-js-client/lib.es5/node/fingerprint.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/fingerprint'>;
}
declare module 'tus-js-client/lib.es5/node/httpStack.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/httpStack'>;
}
declare module 'tus-js-client/lib.es5/node/index' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node'>;
}
declare module 'tus-js-client/lib.es5/node/index.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node'>;
}
declare module 'tus-js-client/lib.es5/node/isReactNative.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/isReactNative'>;
}
declare module 'tus-js-client/lib.es5/node/request.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/request'>;
}
declare module 'tus-js-client/lib.es5/node/source.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/source'>;
}
declare module 'tus-js-client/lib.es5/node/sources/BufferSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/sources/BufferSource'>;
}
declare module 'tus-js-client/lib.es5/node/sources/FileSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/sources/FileSource'>;
}
declare module 'tus-js-client/lib.es5/node/sources/SlicingStream.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/sources/SlicingStream'>;
}
declare module 'tus-js-client/lib.es5/node/sources/StreamSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/sources/StreamSource'>;
}
declare module 'tus-js-client/lib.es5/node/storage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/storage'>;
}
declare module 'tus-js-client/lib.es5/node/urlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/node/urlStorage'>;
}
declare module 'tus-js-client/lib.es5/noopUrlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/noopUrlStorage'>;
}
declare module 'tus-js-client/lib.es5/upload.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/upload'>;
}
declare module 'tus-js-client/lib.es5/urlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/urlStorage'>;
}
declare module 'tus-js-client/lib.es5/uuid.js' {
  declare module.exports: $Exports<'tus-js-client/lib.es5/uuid'>;
}
declare module 'tus-js-client/lib.esm/browser/fileReader.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/fileReader'>;
}
declare module 'tus-js-client/lib.esm/browser/fingerprint.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/fingerprint'>;
}
declare module 'tus-js-client/lib.esm/browser/httpStack.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/httpStack'>;
}
declare module 'tus-js-client/lib.esm/browser/index' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser'>;
}
declare module 'tus-js-client/lib.esm/browser/index.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser'>;
}
declare module 'tus-js-client/lib.esm/browser/isCordova.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/isCordova'>;
}
declare module 'tus-js-client/lib.esm/browser/isReactNative.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/isReactNative'>;
}
declare module 'tus-js-client/lib.esm/browser/readAsByteArray.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/readAsByteArray'>;
}
declare module 'tus-js-client/lib.esm/browser/sources/FileSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/sources/FileSource'>;
}
declare module 'tus-js-client/lib.esm/browser/sources/isCordova.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/sources/isCordova'>;
}
declare module 'tus-js-client/lib.esm/browser/sources/readAsByteArray.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/sources/readAsByteArray'>;
}
declare module 'tus-js-client/lib.esm/browser/sources/StreamSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/sources/StreamSource'>;
}
declare module 'tus-js-client/lib.esm/browser/uriToBlob.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/uriToBlob'>;
}
declare module 'tus-js-client/lib.esm/browser/urlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/browser/urlStorage'>;
}
declare module 'tus-js-client/lib.esm/error.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/error'>;
}
declare module 'tus-js-client/lib.esm/logger.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/logger'>;
}
declare module 'tus-js-client/lib.esm/node/fileReader.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/fileReader'>;
}
declare module 'tus-js-client/lib.esm/node/fingerprint.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/fingerprint'>;
}
declare module 'tus-js-client/lib.esm/node/httpStack.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/httpStack'>;
}
declare module 'tus-js-client/lib.esm/node/index' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node'>;
}
declare module 'tus-js-client/lib.esm/node/index.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node'>;
}
declare module 'tus-js-client/lib.esm/node/sources/BufferSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/sources/BufferSource'>;
}
declare module 'tus-js-client/lib.esm/node/sources/FileSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/sources/FileSource'>;
}
declare module 'tus-js-client/lib.esm/node/sources/SlicingStream.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/sources/SlicingStream'>;
}
declare module 'tus-js-client/lib.esm/node/sources/StreamSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/sources/StreamSource'>;
}
declare module 'tus-js-client/lib.esm/node/urlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/node/urlStorage'>;
}
declare module 'tus-js-client/lib.esm/noopUrlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/noopUrlStorage'>;
}
declare module 'tus-js-client/lib.esm/upload.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/upload'>;
}
declare module 'tus-js-client/lib.esm/uuid.js' {
  declare module.exports: $Exports<'tus-js-client/lib.esm/uuid'>;
}
declare module 'tus-js-client/lib/browser/fileReader.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/fileReader'>;
}
declare module 'tus-js-client/lib/browser/fingerprint.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/fingerprint'>;
}
declare module 'tus-js-client/lib/browser/httpStack.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/httpStack'>;
}
declare module 'tus-js-client/lib/browser/index' {
  declare module.exports: $Exports<'tus-js-client/lib/browser'>;
}
declare module 'tus-js-client/lib/browser/index.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser'>;
}
declare module 'tus-js-client/lib/browser/isReactNative.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/isReactNative'>;
}
declare module 'tus-js-client/lib/browser/sources/FileSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/sources/FileSource'>;
}
declare module 'tus-js-client/lib/browser/sources/isCordova.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/sources/isCordova'>;
}
declare module 'tus-js-client/lib/browser/sources/readAsByteArray.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/sources/readAsByteArray'>;
}
declare module 'tus-js-client/lib/browser/sources/StreamSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/sources/StreamSource'>;
}
declare module 'tus-js-client/lib/browser/uriToBlob.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/uriToBlob'>;
}
declare module 'tus-js-client/lib/browser/urlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib/browser/urlStorage'>;
}
declare module 'tus-js-client/lib/error.js' {
  declare module.exports: $Exports<'tus-js-client/lib/error'>;
}
declare module 'tus-js-client/lib/logger.js' {
  declare module.exports: $Exports<'tus-js-client/lib/logger'>;
}
declare module 'tus-js-client/lib/node/fileReader.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/fileReader'>;
}
declare module 'tus-js-client/lib/node/fingerprint.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/fingerprint'>;
}
declare module 'tus-js-client/lib/node/httpStack.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/httpStack'>;
}
declare module 'tus-js-client/lib/node/index' {
  declare module.exports: $Exports<'tus-js-client/lib/node'>;
}
declare module 'tus-js-client/lib/node/index.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node'>;
}
declare module 'tus-js-client/lib/node/sources/BufferSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/sources/BufferSource'>;
}
declare module 'tus-js-client/lib/node/sources/FileSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/sources/FileSource'>;
}
declare module 'tus-js-client/lib/node/sources/SlicingStream.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/sources/SlicingStream'>;
}
declare module 'tus-js-client/lib/node/sources/StreamSource.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/sources/StreamSource'>;
}
declare module 'tus-js-client/lib/node/urlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib/node/urlStorage'>;
}
declare module 'tus-js-client/lib/noopUrlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/lib/noopUrlStorage'>;
}
declare module 'tus-js-client/lib/upload.js' {
  declare module.exports: $Exports<'tus-js-client/lib/upload'>;
}
declare module 'tus-js-client/lib/uuid.js' {
  declare module.exports: $Exports<'tus-js-client/lib/uuid'>;
}
declare module 'tus-js-client/test/spec/browser-index.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/browser-index'>;
}
declare module 'tus-js-client/test/spec/helpers/assertUrlStorage.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/helpers/assertUrlStorage'>;
}
declare module 'tus-js-client/test/spec/helpers/puppeteer/reporter.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/helpers/puppeteer/reporter'>;
}
declare module 'tus-js-client/test/spec/helpers/utils.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/helpers/utils'>;
}
declare module 'tus-js-client/test/spec/node-index.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/node-index'>;
}
declare module 'tus-js-client/test/spec/test-browser-specific.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/test-browser-specific'>;
}
declare module 'tus-js-client/test/spec/test-common.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/test-common'>;
}
declare module 'tus-js-client/test/spec/test-end-to-end.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/test-end-to-end'>;
}
declare module 'tus-js-client/test/spec/test-node-specific.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/test-node-specific'>;
}
declare module 'tus-js-client/test/spec/test-parallel-uploads.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/test-parallel-uploads'>;
}
declare module 'tus-js-client/test/spec/test-terminate.js' {
  declare module.exports: $Exports<'tus-js-client/test/spec/test-terminate'>;
}
