// flow-typed signature: 820a25bfa2557859dd6062c6180e01e4
// flow-typed version: <<STUB>>/twemoji_v^14.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twemoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twemoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twemoji/dist/twemoji.amd' {
  declare module.exports: any;
}

declare module 'twemoji/dist/twemoji.esm' {
  declare module.exports: any;
}

declare module 'twemoji/dist/twemoji' {
  declare module.exports: any;
}

declare module 'twemoji/dist/twemoji.min' {
  declare module.exports: any;
}

declare module 'twemoji/dist/twemoji.npm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twemoji/dist/twemoji.amd.js' {
  declare module.exports: $Exports<'twemoji/dist/twemoji.amd'>;
}
declare module 'twemoji/dist/twemoji.esm.js' {
  declare module.exports: $Exports<'twemoji/dist/twemoji.esm'>;
}
declare module 'twemoji/dist/twemoji.js' {
  declare module.exports: $Exports<'twemoji/dist/twemoji'>;
}
declare module 'twemoji/dist/twemoji.min.js' {
  declare module.exports: $Exports<'twemoji/dist/twemoji.min'>;
}
declare module 'twemoji/dist/twemoji.npm.js' {
  declare module.exports: $Exports<'twemoji/dist/twemoji.npm'>;
}
