// flow-typed signature: 074ac5877f80ebac7998ac0ccdd7b9cd
// flow-typed version: <<STUB>>/vast-client_v^3.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vast-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vast-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vast-client/bundle_size' {
  declare module.exports: any;
}

declare module 'vast-client/dist/vast-client-browser.min' {
  declare module.exports: any;
}

declare module 'vast-client/dist/vast-client-node' {
  declare module.exports: any;
}

declare module 'vast-client/dist/vast-client-node.min' {
  declare module.exports: any;
}

declare module 'vast-client/dist/vast-client' {
  declare module.exports: any;
}

declare module 'vast-client/dist/vast-client.min' {
  declare module.exports: any;
}

declare module 'vast-client/jest.config' {
  declare module.exports: any;
}

declare module 'vast-client/performance/get_time' {
  declare module.exports: any;
}

declare module 'vast-client/performance/parse_time' {
  declare module.exports: any;
}

declare module 'vast-client/performance/performance_test' {
  declare module.exports: any;
}

declare module 'vast-client/rollup.config' {
  declare module.exports: any;
}

declare module 'vast-client/spec/ad_parser.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/bitrate.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/creative_companion_parser.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/creatives_parser.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/event_emitter.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/extensions_parser.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/parser_utils.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/ad_verification_extension_and_node' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/ad_verification_extentions' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/companion_ads' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/creatives' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/extensions' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/inline_missing_values' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/inline_trackers' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/linear_ads' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/viewable_impression' {
  declare module.exports: any;
}

declare module 'vast-client/spec/samples/wrapper_missing_values' {
  declare module.exports: any;
}

declare module 'vast-client/spec/util.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/utils/utils' {
  declare module.exports: any;
}

declare module 'vast-client/spec/vast_client.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/vast_parser.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/vast_trackers.spec' {
  declare module.exports: any;
}

declare module 'vast-client/spec/vast_verification.spec' {
  declare module.exports: any;
}

declare module 'vast-client/src/ad_verification' {
  declare module.exports: any;
}

declare module 'vast-client/src/ad' {
  declare module.exports: any;
}

declare module 'vast-client/src/closed_caption_file' {
  declare module.exports: any;
}

declare module 'vast-client/src/companion_ad' {
  declare module.exports: any;
}

declare module 'vast-client/src/creative/creative_companion' {
  declare module.exports: any;
}

declare module 'vast-client/src/creative/creative_linear' {
  declare module.exports: any;
}

declare module 'vast-client/src/creative/creative_non_linear' {
  declare module.exports: any;
}

declare module 'vast-client/src/creative/creative' {
  declare module.exports: any;
}

declare module 'vast-client/src/extension' {
  declare module.exports: any;
}

declare module 'vast-client/src/icon' {
  declare module.exports: any;
}

declare module 'vast-client/src' {
  declare module.exports: any;
}

declare module 'vast-client/src/interactive_creative_file' {
  declare module.exports: any;
}

declare module 'vast-client/src/media_file' {
  declare module.exports: any;
}

declare module 'vast-client/src/mezzanine' {
  declare module.exports: any;
}

declare module 'vast-client/src/non_linear_ad' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/ad_parser' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/bitrate' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/creative_companion_parser' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/creative_linear_parser' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/creative_non_linear_parser' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/creatives_parser' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/extensions_parser' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/parser_utils' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/parser_verification' {
  declare module.exports: any;
}

declare module 'vast-client/src/parser/vast_parser' {
  declare module.exports: any;
}

declare module 'vast-client/src/url_handler' {
  declare module.exports: any;
}

declare module 'vast-client/src/urlhandlers/consts' {
  declare module.exports: any;
}

declare module 'vast-client/src/urlhandlers/mock_node_url_handler' {
  declare module.exports: any;
}

declare module 'vast-client/src/urlhandlers/node_url_handler' {
  declare module.exports: any;
}

declare module 'vast-client/src/urlhandlers/xhr_url_handler' {
  declare module.exports: any;
}

declare module 'vast-client/src/util/event_emitter' {
  declare module.exports: any;
}

declare module 'vast-client/src/util/macros' {
  declare module.exports: any;
}

declare module 'vast-client/src/util/requiredValues' {
  declare module.exports: any;
}

declare module 'vast-client/src/util/storage' {
  declare module.exports: any;
}

declare module 'vast-client/src/util/util' {
  declare module.exports: any;
}

declare module 'vast-client/src/vast_client' {
  declare module.exports: any;
}

declare module 'vast-client/src/vast_response' {
  declare module.exports: any;
}

declare module 'vast-client/src/vast_tracker' {
  declare module.exports: any;
}

declare module 'vast-client/test/vast_parser' {
  declare module.exports: any;
}

declare module 'vast-client/test/vast_tracker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vast-client/bundle_size.js' {
  declare module.exports: $Exports<'vast-client/bundle_size'>;
}
declare module 'vast-client/dist/vast-client-browser.min.js' {
  declare module.exports: $Exports<'vast-client/dist/vast-client-browser.min'>;
}
declare module 'vast-client/dist/vast-client-node.js' {
  declare module.exports: $Exports<'vast-client/dist/vast-client-node'>;
}
declare module 'vast-client/dist/vast-client-node.min.js' {
  declare module.exports: $Exports<'vast-client/dist/vast-client-node.min'>;
}
declare module 'vast-client/dist/vast-client.js' {
  declare module.exports: $Exports<'vast-client/dist/vast-client'>;
}
declare module 'vast-client/dist/vast-client.min.js' {
  declare module.exports: $Exports<'vast-client/dist/vast-client.min'>;
}
declare module 'vast-client/jest.config.js' {
  declare module.exports: $Exports<'vast-client/jest.config'>;
}
declare module 'vast-client/performance/get_time.js' {
  declare module.exports: $Exports<'vast-client/performance/get_time'>;
}
declare module 'vast-client/performance/parse_time.js' {
  declare module.exports: $Exports<'vast-client/performance/parse_time'>;
}
declare module 'vast-client/performance/performance_test.js' {
  declare module.exports: $Exports<'vast-client/performance/performance_test'>;
}
declare module 'vast-client/rollup.config.js' {
  declare module.exports: $Exports<'vast-client/rollup.config'>;
}
declare module 'vast-client/spec/ad_parser.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/ad_parser.spec'>;
}
declare module 'vast-client/spec/bitrate.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/bitrate.spec'>;
}
declare module 'vast-client/spec/creative_companion_parser.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/creative_companion_parser.spec'>;
}
declare module 'vast-client/spec/creatives_parser.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/creatives_parser.spec'>;
}
declare module 'vast-client/spec/event_emitter.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/event_emitter.spec'>;
}
declare module 'vast-client/spec/extensions_parser.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/extensions_parser.spec'>;
}
declare module 'vast-client/spec/parser_utils.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/parser_utils.spec'>;
}
declare module 'vast-client/spec/samples/ad_verification_extension_and_node.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/ad_verification_extension_and_node'>;
}
declare module 'vast-client/spec/samples/ad_verification_extentions.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/ad_verification_extentions'>;
}
declare module 'vast-client/spec/samples/companion_ads.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/companion_ads'>;
}
declare module 'vast-client/spec/samples/creatives.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/creatives'>;
}
declare module 'vast-client/spec/samples/extensions.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/extensions'>;
}
declare module 'vast-client/spec/samples/inline_missing_values.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/inline_missing_values'>;
}
declare module 'vast-client/spec/samples/inline_trackers.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/inline_trackers'>;
}
declare module 'vast-client/spec/samples/linear_ads.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/linear_ads'>;
}
declare module 'vast-client/spec/samples/viewable_impression.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/viewable_impression'>;
}
declare module 'vast-client/spec/samples/wrapper_missing_values.js' {
  declare module.exports: $Exports<'vast-client/spec/samples/wrapper_missing_values'>;
}
declare module 'vast-client/spec/util.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/util.spec'>;
}
declare module 'vast-client/spec/utils/utils.js' {
  declare module.exports: $Exports<'vast-client/spec/utils/utils'>;
}
declare module 'vast-client/spec/vast_client.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/vast_client.spec'>;
}
declare module 'vast-client/spec/vast_parser.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/vast_parser.spec'>;
}
declare module 'vast-client/spec/vast_trackers.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/vast_trackers.spec'>;
}
declare module 'vast-client/spec/vast_verification.spec.js' {
  declare module.exports: $Exports<'vast-client/spec/vast_verification.spec'>;
}
declare module 'vast-client/src/ad_verification.js' {
  declare module.exports: $Exports<'vast-client/src/ad_verification'>;
}
declare module 'vast-client/src/ad.js' {
  declare module.exports: $Exports<'vast-client/src/ad'>;
}
declare module 'vast-client/src/closed_caption_file.js' {
  declare module.exports: $Exports<'vast-client/src/closed_caption_file'>;
}
declare module 'vast-client/src/companion_ad.js' {
  declare module.exports: $Exports<'vast-client/src/companion_ad'>;
}
declare module 'vast-client/src/creative/creative_companion.js' {
  declare module.exports: $Exports<'vast-client/src/creative/creative_companion'>;
}
declare module 'vast-client/src/creative/creative_linear.js' {
  declare module.exports: $Exports<'vast-client/src/creative/creative_linear'>;
}
declare module 'vast-client/src/creative/creative_non_linear.js' {
  declare module.exports: $Exports<'vast-client/src/creative/creative_non_linear'>;
}
declare module 'vast-client/src/creative/creative.js' {
  declare module.exports: $Exports<'vast-client/src/creative/creative'>;
}
declare module 'vast-client/src/extension.js' {
  declare module.exports: $Exports<'vast-client/src/extension'>;
}
declare module 'vast-client/src/icon.js' {
  declare module.exports: $Exports<'vast-client/src/icon'>;
}
declare module 'vast-client/src/index' {
  declare module.exports: $Exports<'vast-client/src'>;
}
declare module 'vast-client/src/index.js' {
  declare module.exports: $Exports<'vast-client/src'>;
}
declare module 'vast-client/src/interactive_creative_file.js' {
  declare module.exports: $Exports<'vast-client/src/interactive_creative_file'>;
}
declare module 'vast-client/src/media_file.js' {
  declare module.exports: $Exports<'vast-client/src/media_file'>;
}
declare module 'vast-client/src/mezzanine.js' {
  declare module.exports: $Exports<'vast-client/src/mezzanine'>;
}
declare module 'vast-client/src/non_linear_ad.js' {
  declare module.exports: $Exports<'vast-client/src/non_linear_ad'>;
}
declare module 'vast-client/src/parser/ad_parser.js' {
  declare module.exports: $Exports<'vast-client/src/parser/ad_parser'>;
}
declare module 'vast-client/src/parser/bitrate.js' {
  declare module.exports: $Exports<'vast-client/src/parser/bitrate'>;
}
declare module 'vast-client/src/parser/creative_companion_parser.js' {
  declare module.exports: $Exports<'vast-client/src/parser/creative_companion_parser'>;
}
declare module 'vast-client/src/parser/creative_linear_parser.js' {
  declare module.exports: $Exports<'vast-client/src/parser/creative_linear_parser'>;
}
declare module 'vast-client/src/parser/creative_non_linear_parser.js' {
  declare module.exports: $Exports<'vast-client/src/parser/creative_non_linear_parser'>;
}
declare module 'vast-client/src/parser/creatives_parser.js' {
  declare module.exports: $Exports<'vast-client/src/parser/creatives_parser'>;
}
declare module 'vast-client/src/parser/extensions_parser.js' {
  declare module.exports: $Exports<'vast-client/src/parser/extensions_parser'>;
}
declare module 'vast-client/src/parser/parser_utils.js' {
  declare module.exports: $Exports<'vast-client/src/parser/parser_utils'>;
}
declare module 'vast-client/src/parser/parser_verification.js' {
  declare module.exports: $Exports<'vast-client/src/parser/parser_verification'>;
}
declare module 'vast-client/src/parser/vast_parser.js' {
  declare module.exports: $Exports<'vast-client/src/parser/vast_parser'>;
}
declare module 'vast-client/src/url_handler.js' {
  declare module.exports: $Exports<'vast-client/src/url_handler'>;
}
declare module 'vast-client/src/urlhandlers/consts.js' {
  declare module.exports: $Exports<'vast-client/src/urlhandlers/consts'>;
}
declare module 'vast-client/src/urlhandlers/mock_node_url_handler.js' {
  declare module.exports: $Exports<'vast-client/src/urlhandlers/mock_node_url_handler'>;
}
declare module 'vast-client/src/urlhandlers/node_url_handler.js' {
  declare module.exports: $Exports<'vast-client/src/urlhandlers/node_url_handler'>;
}
declare module 'vast-client/src/urlhandlers/xhr_url_handler.js' {
  declare module.exports: $Exports<'vast-client/src/urlhandlers/xhr_url_handler'>;
}
declare module 'vast-client/src/util/event_emitter.js' {
  declare module.exports: $Exports<'vast-client/src/util/event_emitter'>;
}
declare module 'vast-client/src/util/macros.js' {
  declare module.exports: $Exports<'vast-client/src/util/macros'>;
}
declare module 'vast-client/src/util/requiredValues.js' {
  declare module.exports: $Exports<'vast-client/src/util/requiredValues'>;
}
declare module 'vast-client/src/util/storage.js' {
  declare module.exports: $Exports<'vast-client/src/util/storage'>;
}
declare module 'vast-client/src/util/util.js' {
  declare module.exports: $Exports<'vast-client/src/util/util'>;
}
declare module 'vast-client/src/vast_client.js' {
  declare module.exports: $Exports<'vast-client/src/vast_client'>;
}
declare module 'vast-client/src/vast_response.js' {
  declare module.exports: $Exports<'vast-client/src/vast_response'>;
}
declare module 'vast-client/src/vast_tracker.js' {
  declare module.exports: $Exports<'vast-client/src/vast_tracker'>;
}
declare module 'vast-client/test/vast_parser.js' {
  declare module.exports: $Exports<'vast-client/test/vast_parser'>;
}
declare module 'vast-client/test/vast_tracker.js' {
  declare module.exports: $Exports<'vast-client/test/vast_tracker'>;
}
