// flow-typed signature: 86a6d9340bdfce136f8b78cbe17985db
// flow-typed version: <<STUB>>/videojs-event-tracking_v^1.0.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-event-tracking'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-event-tracking' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-event-tracking/dist/videojs-event-tracking.cjs' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/dist/videojs-event-tracking.es' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/dist/videojs-event-tracking' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/dist/videojs-event-tracking.min' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/scripts/modules.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/scripts/test.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/scripts/umd.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/scripts/version' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/src/plugin' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/src/tracking/buffering' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/src/tracking/pause' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/src/tracking/percentile' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/src/tracking/performance' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/src/tracking/play' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/src/tracking/seek' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/test/dist/bundle' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/test/karma.conf' {
  declare module.exports: any;
}

declare module 'videojs-event-tracking/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-event-tracking/dist/videojs-event-tracking.cjs.js' {
  declare module.exports: $Exports<'videojs-event-tracking/dist/videojs-event-tracking.cjs'>;
}
declare module 'videojs-event-tracking/dist/videojs-event-tracking.es.js' {
  declare module.exports: $Exports<'videojs-event-tracking/dist/videojs-event-tracking.es'>;
}
declare module 'videojs-event-tracking/dist/videojs-event-tracking.js' {
  declare module.exports: $Exports<'videojs-event-tracking/dist/videojs-event-tracking'>;
}
declare module 'videojs-event-tracking/dist/videojs-event-tracking.min.js' {
  declare module.exports: $Exports<'videojs-event-tracking/dist/videojs-event-tracking.min'>;
}
declare module 'videojs-event-tracking/scripts/modules.rollup.config.js' {
  declare module.exports: $Exports<'videojs-event-tracking/scripts/modules.rollup.config'>;
}
declare module 'videojs-event-tracking/scripts/test.rollup.config.js' {
  declare module.exports: $Exports<'videojs-event-tracking/scripts/test.rollup.config'>;
}
declare module 'videojs-event-tracking/scripts/umd.rollup.config.js' {
  declare module.exports: $Exports<'videojs-event-tracking/scripts/umd.rollup.config'>;
}
declare module 'videojs-event-tracking/scripts/version.js' {
  declare module.exports: $Exports<'videojs-event-tracking/scripts/version'>;
}
declare module 'videojs-event-tracking/src/plugin.js' {
  declare module.exports: $Exports<'videojs-event-tracking/src/plugin'>;
}
declare module 'videojs-event-tracking/src/tracking/buffering.js' {
  declare module.exports: $Exports<'videojs-event-tracking/src/tracking/buffering'>;
}
declare module 'videojs-event-tracking/src/tracking/pause.js' {
  declare module.exports: $Exports<'videojs-event-tracking/src/tracking/pause'>;
}
declare module 'videojs-event-tracking/src/tracking/percentile.js' {
  declare module.exports: $Exports<'videojs-event-tracking/src/tracking/percentile'>;
}
declare module 'videojs-event-tracking/src/tracking/performance.js' {
  declare module.exports: $Exports<'videojs-event-tracking/src/tracking/performance'>;
}
declare module 'videojs-event-tracking/src/tracking/play.js' {
  declare module.exports: $Exports<'videojs-event-tracking/src/tracking/play'>;
}
declare module 'videojs-event-tracking/src/tracking/seek.js' {
  declare module.exports: $Exports<'videojs-event-tracking/src/tracking/seek'>;
}
declare module 'videojs-event-tracking/test/dist/bundle.js' {
  declare module.exports: $Exports<'videojs-event-tracking/test/dist/bundle'>;
}
declare module 'videojs-event-tracking/test/karma.conf.js' {
  declare module.exports: $Exports<'videojs-event-tracking/test/karma.conf'>;
}
declare module 'videojs-event-tracking/test/plugin.test.js' {
  declare module.exports: $Exports<'videojs-event-tracking/test/plugin.test'>;
}
