// flow-typed signature: ca074cb79443e653b22fa72e5c5ba1da
// flow-typed version: <<STUB>>/videojs-ima-player_v^0.5.6/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-ima-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-ima-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-ima-player/dist/videojs.ima' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/dist/videojs.ima.min' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/advanced/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/autoplay/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/dash/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/hls/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/manualplay/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/multiple/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/playlist/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/reactjs/ads' {
  declare module.exports: any;
}

declare module 'videojs-ima-player/examples/simple/ads' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-ima-player/dist/videojs.ima.js' {
  declare module.exports: $Exports<'videojs-ima-player/dist/videojs.ima'>;
}
declare module 'videojs-ima-player/dist/videojs.ima.min.js' {
  declare module.exports: $Exports<'videojs-ima-player/dist/videojs.ima.min'>;
}
declare module 'videojs-ima-player/examples/advanced/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/advanced/ads'>;
}
declare module 'videojs-ima-player/examples/autoplay/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/autoplay/ads'>;
}
declare module 'videojs-ima-player/examples/dash/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/dash/ads'>;
}
declare module 'videojs-ima-player/examples/hls/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/hls/ads'>;
}
declare module 'videojs-ima-player/examples/manualplay/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/manualplay/ads'>;
}
declare module 'videojs-ima-player/examples/multiple/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/multiple/ads'>;
}
declare module 'videojs-ima-player/examples/playlist/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/playlist/ads'>;
}
declare module 'videojs-ima-player/examples/reactjs/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/reactjs/ads'>;
}
declare module 'videojs-ima-player/examples/simple/ads.js' {
  declare module.exports: $Exports<'videojs-ima-player/examples/simple/ads'>;
}
