// flow-typed signature: 778ce831684d118f2ea84690bb409d66
// flow-typed version: <<STUB>>/videojs-contrib-ads_v^6.9.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-contrib-ads'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-contrib-ads' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-contrib-ads/dist/videojs-contrib-ads.cjs' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/dist/videojs-contrib-ads.es' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/dist/videojs-contrib-ads' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/dist/videojs-contrib-ads.min' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/dist/videojs.ads' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/dist/videojs.ads.min' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/docs/developer/lib/railroad-diagrams' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/scripts/karma.conf' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/scripts/rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/adBreak' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/ads' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/cancelContentPlay' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/contentupdate' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/cueTextTracks' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/macros' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/playMiddleware' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/plugin' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/redispatch' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/register' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/snapshot' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/abstract/AdState' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/abstract/ContentState' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/abstract/State' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/AdsDone' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/BeforePreroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/ContentPlayback' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/Midroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/Postroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/Preroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/StitchedAdRoll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/states/StitchedContentPlayback' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/src/tcf' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/dist/bundle' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/lib/shared-module-hooks' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.ads' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.cancelContentPlay' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.cueTextTracks' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.events-midroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.events-no-postroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.events-no-preroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.events-postroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.events-preroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.macros' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.playMiddleware' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.snapshot' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/integration/test.stitchedAds' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/abstract/test.AdState' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/abstract/test.ContentState' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/abstract/test.State' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.AdsDone' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.BeforePreroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.ContentPlayback' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.Midroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.Postroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.Preroll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.StitchedAdRoll' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/states/test.StitchedContentPlayback' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/test.ads' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/test.playMiddleware' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/test.redispatch' {
  declare module.exports: any;
}

declare module 'videojs-contrib-ads/test/unit/test.register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-contrib-ads/dist/videojs-contrib-ads.cjs.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/dist/videojs-contrib-ads.cjs'>;
}
declare module 'videojs-contrib-ads/dist/videojs-contrib-ads.es.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/dist/videojs-contrib-ads.es'>;
}
declare module 'videojs-contrib-ads/dist/videojs-contrib-ads.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/dist/videojs-contrib-ads'>;
}
declare module 'videojs-contrib-ads/dist/videojs-contrib-ads.min.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/dist/videojs-contrib-ads.min'>;
}
declare module 'videojs-contrib-ads/dist/videojs.ads.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/dist/videojs.ads'>;
}
declare module 'videojs-contrib-ads/dist/videojs.ads.min.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/dist/videojs.ads.min'>;
}
declare module 'videojs-contrib-ads/docs/developer/lib/railroad-diagrams.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/docs/developer/lib/railroad-diagrams'>;
}
declare module 'videojs-contrib-ads/scripts/karma.conf.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/scripts/karma.conf'>;
}
declare module 'videojs-contrib-ads/scripts/rollup.config.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/scripts/rollup.config'>;
}
declare module 'videojs-contrib-ads/src/adBreak.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/adBreak'>;
}
declare module 'videojs-contrib-ads/src/ads.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/ads'>;
}
declare module 'videojs-contrib-ads/src/cancelContentPlay.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/cancelContentPlay'>;
}
declare module 'videojs-contrib-ads/src/contentupdate.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/contentupdate'>;
}
declare module 'videojs-contrib-ads/src/cueTextTracks.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/cueTextTracks'>;
}
declare module 'videojs-contrib-ads/src/macros.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/macros'>;
}
declare module 'videojs-contrib-ads/src/playMiddleware.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/playMiddleware'>;
}
declare module 'videojs-contrib-ads/src/plugin.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/plugin'>;
}
declare module 'videojs-contrib-ads/src/redispatch.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/redispatch'>;
}
declare module 'videojs-contrib-ads/src/register.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/register'>;
}
declare module 'videojs-contrib-ads/src/snapshot.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/snapshot'>;
}
declare module 'videojs-contrib-ads/src/states.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states'>;
}
declare module 'videojs-contrib-ads/src/states/abstract/AdState.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/abstract/AdState'>;
}
declare module 'videojs-contrib-ads/src/states/abstract/ContentState.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/abstract/ContentState'>;
}
declare module 'videojs-contrib-ads/src/states/abstract/State.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/abstract/State'>;
}
declare module 'videojs-contrib-ads/src/states/AdsDone.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/AdsDone'>;
}
declare module 'videojs-contrib-ads/src/states/BeforePreroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/BeforePreroll'>;
}
declare module 'videojs-contrib-ads/src/states/ContentPlayback.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/ContentPlayback'>;
}
declare module 'videojs-contrib-ads/src/states/Midroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/Midroll'>;
}
declare module 'videojs-contrib-ads/src/states/Postroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/Postroll'>;
}
declare module 'videojs-contrib-ads/src/states/Preroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/Preroll'>;
}
declare module 'videojs-contrib-ads/src/states/StitchedAdRoll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/StitchedAdRoll'>;
}
declare module 'videojs-contrib-ads/src/states/StitchedContentPlayback.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/states/StitchedContentPlayback'>;
}
declare module 'videojs-contrib-ads/src/tcf.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/src/tcf'>;
}
declare module 'videojs-contrib-ads/test/dist/bundle.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/dist/bundle'>;
}
declare module 'videojs-contrib-ads/test/integration/lib/shared-module-hooks.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/lib/shared-module-hooks'>;
}
declare module 'videojs-contrib-ads/test/integration/test.ads.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.ads'>;
}
declare module 'videojs-contrib-ads/test/integration/test.cancelContentPlay.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.cancelContentPlay'>;
}
declare module 'videojs-contrib-ads/test/integration/test.cueTextTracks.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.cueTextTracks'>;
}
declare module 'videojs-contrib-ads/test/integration/test.events-midroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.events-midroll'>;
}
declare module 'videojs-contrib-ads/test/integration/test.events-no-postroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.events-no-postroll'>;
}
declare module 'videojs-contrib-ads/test/integration/test.events-no-preroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.events-no-preroll'>;
}
declare module 'videojs-contrib-ads/test/integration/test.events-postroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.events-postroll'>;
}
declare module 'videojs-contrib-ads/test/integration/test.events-preroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.events-preroll'>;
}
declare module 'videojs-contrib-ads/test/integration/test.macros.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.macros'>;
}
declare module 'videojs-contrib-ads/test/integration/test.playMiddleware.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.playMiddleware'>;
}
declare module 'videojs-contrib-ads/test/integration/test.snapshot.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.snapshot'>;
}
declare module 'videojs-contrib-ads/test/integration/test.stitchedAds.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/integration/test.stitchedAds'>;
}
declare module 'videojs-contrib-ads/test/unit/states/abstract/test.AdState.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/abstract/test.AdState'>;
}
declare module 'videojs-contrib-ads/test/unit/states/abstract/test.ContentState.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/abstract/test.ContentState'>;
}
declare module 'videojs-contrib-ads/test/unit/states/abstract/test.State.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/abstract/test.State'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.AdsDone.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.AdsDone'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.BeforePreroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.BeforePreroll'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.ContentPlayback.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.ContentPlayback'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.Midroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.Midroll'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.Postroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.Postroll'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.Preroll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.Preroll'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.StitchedAdRoll.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.StitchedAdRoll'>;
}
declare module 'videojs-contrib-ads/test/unit/states/test.StitchedContentPlayback.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/states/test.StitchedContentPlayback'>;
}
declare module 'videojs-contrib-ads/test/unit/test.ads.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/test.ads'>;
}
declare module 'videojs-contrib-ads/test/unit/test.playMiddleware.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/test.playMiddleware'>;
}
declare module 'videojs-contrib-ads/test/unit/test.redispatch.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/test.redispatch'>;
}
declare module 'videojs-contrib-ads/test/unit/test.register.js' {
  declare module.exports: $Exports<'videojs-contrib-ads/test/unit/test.register'>;
}
