// flow-typed signature: 1c69fb3ffe2a7d844750b76f12793b54
// flow-typed version: <<STUB>>/videojs-vtt-thumbnails_vhttps://github.com/OdyseeTeam/videojs-vtt-thumbnails/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-vtt-thumbnails'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-vtt-thumbnails' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.cjs' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.es' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.min' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/scripts/modules.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/scripts/test.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/scripts/umd.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/scripts/version' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/src/plugin' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/test/karma.conf' {
  declare module.exports: any;
}

declare module 'videojs-vtt-thumbnails/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.cjs.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.cjs'>;
}
declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.es.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.es'>;
}
declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails'>;
}
declare module 'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.min.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/dist/videojs-vtt-thumbnails.min'>;
}
declare module 'videojs-vtt-thumbnails/scripts/modules.rollup.config.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/scripts/modules.rollup.config'>;
}
declare module 'videojs-vtt-thumbnails/scripts/test.rollup.config.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/scripts/test.rollup.config'>;
}
declare module 'videojs-vtt-thumbnails/scripts/umd.rollup.config.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/scripts/umd.rollup.config'>;
}
declare module 'videojs-vtt-thumbnails/scripts/version.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/scripts/version'>;
}
declare module 'videojs-vtt-thumbnails/src/plugin.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/src/plugin'>;
}
declare module 'videojs-vtt-thumbnails/test/karma.conf.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/test/karma.conf'>;
}
declare module 'videojs-vtt-thumbnails/test/plugin.test.js' {
  declare module.exports: $Exports<'videojs-vtt-thumbnails/test/plugin.test'>;
}
