// flow-typed signature: 87053c55662a019a53a7de7985ab4787
// flow-typed version: <<STUB>>/videojs-ima_v^1.11.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-ima'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-ima' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-ima/dist/videojs.ima.es' {
  declare module.exports: any;
}

declare module 'videojs-ima/dist/videojs.ima' {
  declare module.exports: any;
}

declare module 'videojs-ima/dist/videojs.ima.min' {
  declare module.exports: any;
}

declare module 'videojs-ima/src/ad-ui' {
  declare module.exports: any;
}

declare module 'videojs-ima/src/controller' {
  declare module.exports: any;
}

declare module 'videojs-ima/src/ima-plugin' {
  declare module.exports: any;
}

declare module 'videojs-ima/src/player-wrapper' {
  declare module.exports: any;
}

declare module 'videojs-ima/src/sdk-impl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-ima/dist/videojs.ima.es.js' {
  declare module.exports: $Exports<'videojs-ima/dist/videojs.ima.es'>;
}
declare module 'videojs-ima/dist/videojs.ima.js' {
  declare module.exports: $Exports<'videojs-ima/dist/videojs.ima'>;
}
declare module 'videojs-ima/dist/videojs.ima.min.js' {
  declare module.exports: $Exports<'videojs-ima/dist/videojs.ima.min'>;
}
declare module 'videojs-ima/src/ad-ui.js' {
  declare module.exports: $Exports<'videojs-ima/src/ad-ui'>;
}
declare module 'videojs-ima/src/controller.js' {
  declare module.exports: $Exports<'videojs-ima/src/controller'>;
}
declare module 'videojs-ima/src/ima-plugin.js' {
  declare module.exports: $Exports<'videojs-ima/src/ima-plugin'>;
}
declare module 'videojs-ima/src/player-wrapper.js' {
  declare module.exports: $Exports<'videojs-ima/src/player-wrapper'>;
}
declare module 'videojs-ima/src/sdk-impl.js' {
  declare module.exports: $Exports<'videojs-ima/src/sdk-impl'>;
}
