// flow-typed signature: c97da00be4ca3d9d944820b03c7ebe2e
// flow-typed version: <<STUB>>/videojs-contrib-quality-levels_v^2.0.9/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-contrib-quality-levels'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-contrib-quality-levels' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.cjs' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.es' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.min' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/scripts/karma.conf' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/scripts/rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/src/plugin' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/src/quality-level-list' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/src/quality-level' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/test/dist/bundle' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/test/plugin.test' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/test/quality-level-list.test' {
  declare module.exports: any;
}

declare module 'videojs-contrib-quality-levels/test/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.cjs.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.cjs'>;
}
declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.es.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.es'>;
}
declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels'>;
}
declare module 'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.min.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/dist/videojs-contrib-quality-levels.min'>;
}
declare module 'videojs-contrib-quality-levels/scripts/karma.conf.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/scripts/karma.conf'>;
}
declare module 'videojs-contrib-quality-levels/scripts/rollup.config.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/scripts/rollup.config'>;
}
declare module 'videojs-contrib-quality-levels/src/plugin.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/src/plugin'>;
}
declare module 'videojs-contrib-quality-levels/src/quality-level-list.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/src/quality-level-list'>;
}
declare module 'videojs-contrib-quality-levels/src/quality-level.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/src/quality-level'>;
}
declare module 'videojs-contrib-quality-levels/test/dist/bundle.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/test/dist/bundle'>;
}
declare module 'videojs-contrib-quality-levels/test/plugin.test.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/test/plugin.test'>;
}
declare module 'videojs-contrib-quality-levels/test/quality-level-list.test.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/test/quality-level-list.test'>;
}
declare module 'videojs-contrib-quality-levels/test/test-helpers.js' {
  declare module.exports: $Exports<'videojs-contrib-quality-levels/test/test-helpers'>;
}
