// flow-typed signature: 81fa6dd15a33af4457675877f50da5cd
// flow-typed version: <<STUB>>/videojs-logo_v^2.1.4/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-logo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-logo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-logo/dist/videojs-logo.cjs' {
  declare module.exports: any;
}

declare module 'videojs-logo/dist/videojs-logo.es' {
  declare module.exports: any;
}

declare module 'videojs-logo/dist/videojs-logo' {
  declare module.exports: any;
}

declare module 'videojs-logo/dist/videojs-logo.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-logo/dist/videojs-logo.cjs.js' {
  declare module.exports: $Exports<'videojs-logo/dist/videojs-logo.cjs'>;
}
declare module 'videojs-logo/dist/videojs-logo.es.js' {
  declare module.exports: $Exports<'videojs-logo/dist/videojs-logo.es'>;
}
declare module 'videojs-logo/dist/videojs-logo.js' {
  declare module.exports: $Exports<'videojs-logo/dist/videojs-logo'>;
}
declare module 'videojs-logo/dist/videojs-logo.min.js' {
  declare module.exports: $Exports<'videojs-logo/dist/videojs-logo.min'>;
}
