// flow-typed signature: f88d7720f189a7672db135aeefea4de6
// flow-typed version: <<STUB>>/webpack-dev-server_v^4.7.4/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-server/bin/cli-flags' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/bin/process-arguments' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/bin/webpack-dev-server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/clients/SockJSClient' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/clients/WebSocketClient' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/modules/logger' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/modules/sockjs-client' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/overlay' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/socket' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/createSocketURL' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/getCurrentScriptSource' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/log' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/parseURL' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/reloadApp' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/sendMessage' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/stripAnsi' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/getPort' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/Server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/servers/BaseServer' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/servers/SockJSServer' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/servers/WebsocketServer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-server/bin/cli-flags.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/cli-flags'>;
}
declare module 'webpack-dev-server/bin/process-arguments.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/process-arguments'>;
}
declare module 'webpack-dev-server/bin/webpack-dev-server.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/webpack-dev-server'>;
}
declare module 'webpack-dev-server/client/clients/SockJSClient.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/clients/SockJSClient'>;
}
declare module 'webpack-dev-server/client/clients/WebSocketClient.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/clients/WebSocketClient'>;
}
declare module 'webpack-dev-server/client/index' {
  declare module.exports: $Exports<'webpack-dev-server/client'>;
}
declare module 'webpack-dev-server/client/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client'>;
}
declare module 'webpack-dev-server/client/modules/logger/index' {
  declare module.exports: $Exports<'webpack-dev-server/client/modules/logger'>;
}
declare module 'webpack-dev-server/client/modules/logger/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/modules/logger'>;
}
declare module 'webpack-dev-server/client/modules/sockjs-client/index' {
  declare module.exports: $Exports<'webpack-dev-server/client/modules/sockjs-client'>;
}
declare module 'webpack-dev-server/client/modules/sockjs-client/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/modules/sockjs-client'>;
}
declare module 'webpack-dev-server/client/overlay.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/overlay'>;
}
declare module 'webpack-dev-server/client/socket.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/socket'>;
}
declare module 'webpack-dev-server/client/utils/createSocketURL.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/createSocketURL'>;
}
declare module 'webpack-dev-server/client/utils/getCurrentScriptSource.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/getCurrentScriptSource'>;
}
declare module 'webpack-dev-server/client/utils/log.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/log'>;
}
declare module 'webpack-dev-server/client/utils/parseURL.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/parseURL'>;
}
declare module 'webpack-dev-server/client/utils/reloadApp.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/reloadApp'>;
}
declare module 'webpack-dev-server/client/utils/sendMessage.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/sendMessage'>;
}
declare module 'webpack-dev-server/client/utils/stripAnsi.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/stripAnsi'>;
}
declare module 'webpack-dev-server/lib/getPort.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/getPort'>;
}
declare module 'webpack-dev-server/lib/Server.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/Server'>;
}
declare module 'webpack-dev-server/lib/servers/BaseServer.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/servers/BaseServer'>;
}
declare module 'webpack-dev-server/lib/servers/SockJSServer.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/servers/SockJSServer'>;
}
declare module 'webpack-dev-server/lib/servers/WebsocketServer.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/servers/WebsocketServer'>;
}
