// flow-typed signature: ee113d7ed70490ecd3a71a31d5d7ad51
// flow-typed version: <<STUB>>/webpack-merge_v^5.8.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-merge/dist' {
  declare module.exports: any;
}

declare module 'webpack-merge/dist/join-arrays' {
  declare module.exports: any;
}

declare module 'webpack-merge/dist/merge-with' {
  declare module.exports: any;
}

declare module 'webpack-merge/dist/types' {
  declare module.exports: any;
}

declare module 'webpack-merge/dist/unique' {
  declare module.exports: any;
}

declare module 'webpack-merge/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-merge/dist/index' {
  declare module.exports: $Exports<'webpack-merge/dist'>;
}
declare module 'webpack-merge/dist/index.js' {
  declare module.exports: $Exports<'webpack-merge/dist'>;
}
declare module 'webpack-merge/dist/join-arrays.js' {
  declare module.exports: $Exports<'webpack-merge/dist/join-arrays'>;
}
declare module 'webpack-merge/dist/merge-with.js' {
  declare module.exports: $Exports<'webpack-merge/dist/merge-with'>;
}
declare module 'webpack-merge/dist/types.js' {
  declare module.exports: $Exports<'webpack-merge/dist/types'>;
}
declare module 'webpack-merge/dist/unique.js' {
  declare module.exports: $Exports<'webpack-merge/dist/unique'>;
}
declare module 'webpack-merge/dist/utils.js' {
  declare module.exports: $Exports<'webpack-merge/dist/utils'>;
}
