// flow-typed signature: e92676a784552573dc28d2d6ba8a9cb1
// flow-typed version: <<STUB>>/webpack-dev-middleware_v^5.3.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-middleware/dist' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/middleware' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/utils/compatibleAPI' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/utils/getFilenameFromUrl' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/utils/getPaths' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/utils/ready' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/utils/setupHooks' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/utils/setupOutputFileSystem' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/dist/utils/setupWriteToDisk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-middleware/dist/index' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist'>;
}
declare module 'webpack-dev-middleware/dist/index.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist'>;
}
declare module 'webpack-dev-middleware/dist/middleware.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/middleware'>;
}
declare module 'webpack-dev-middleware/dist/utils/compatibleAPI.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/utils/compatibleAPI'>;
}
declare module 'webpack-dev-middleware/dist/utils/getFilenameFromUrl.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/utils/getFilenameFromUrl'>;
}
declare module 'webpack-dev-middleware/dist/utils/getPaths.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/utils/getPaths'>;
}
declare module 'webpack-dev-middleware/dist/utils/ready.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/utils/ready'>;
}
declare module 'webpack-dev-middleware/dist/utils/setupHooks.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/utils/setupHooks'>;
}
declare module 'webpack-dev-middleware/dist/utils/setupOutputFileSystem.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/utils/setupOutputFileSystem'>;
}
declare module 'webpack-dev-middleware/dist/utils/setupWriteToDisk.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/dist/utils/setupWriteToDisk'>;
}
