// flow-typed signature: 41dfff46010d885cad7b71cae33d9e4e
// flow-typed version: <<STUB>>/@babel/plugin-proposal-decorators_v^7.3.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-decorators/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-decorators/lib/transformer-2023-01' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-decorators/lib/transformer-legacy' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-decorators/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib'>;
}
declare module '@babel/plugin-proposal-decorators/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib'>;
}
declare module '@babel/plugin-proposal-decorators/lib/transformer-2023-01.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib/transformer-2023-01'>;
}
declare module '@babel/plugin-proposal-decorators/lib/transformer-legacy.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib/transformer-legacy'>;
}
