// flow-typed signature: 2e740638c024a7076b5569f6f8a896e1
// flow-typed version: <<STUB>>/@stripe/react-stripe-js_v^1.10.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@stripe/react-stripe-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@stripe/react-stripe-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@stripe/react-stripe-js/dist/react-stripe.esm' {
  declare module.exports: any;
}

declare module '@stripe/react-stripe-js/dist/react-stripe' {
  declare module.exports: any;
}

declare module '@stripe/react-stripe-js/dist/react-stripe.umd' {
  declare module.exports: any;
}

declare module '@stripe/react-stripe-js/dist/react-stripe.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@stripe/react-stripe-js/dist/react-stripe.esm.js' {
  declare module.exports: $Exports<'@stripe/react-stripe-js/dist/react-stripe.esm'>;
}
declare module '@stripe/react-stripe-js/dist/react-stripe.js' {
  declare module.exports: $Exports<'@stripe/react-stripe-js/dist/react-stripe'>;
}
declare module '@stripe/react-stripe-js/dist/react-stripe.umd.js' {
  declare module.exports: $Exports<'@stripe/react-stripe-js/dist/react-stripe.umd'>;
}
declare module '@stripe/react-stripe-js/dist/react-stripe.umd.min.js' {
  declare module.exports: $Exports<'@stripe/react-stripe-js/dist/react-stripe.umd.min'>;
}
