// flow-typed signature: a566d333aba09c4fe88fe58cbd0550b5
// flow-typed version: <<STUB>>/@stripe/stripe-js_v^1.35.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@stripe/stripe-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@stripe/stripe-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@stripe/stripe-js/dist/pure.esm' {
  declare module.exports: any;
}

declare module '@stripe/stripe-js/dist/pure' {
  declare module.exports: any;
}

declare module '@stripe/stripe-js/dist/stripe.esm' {
  declare module.exports: any;
}

declare module '@stripe/stripe-js/dist/stripe' {
  declare module.exports: any;
}

declare module '@stripe/stripe-js/pure' {
  declare module.exports: any;
}

// Filename aliases
declare module '@stripe/stripe-js/dist/pure.esm.js' {
  declare module.exports: $Exports<'@stripe/stripe-js/dist/pure.esm'>;
}
declare module '@stripe/stripe-js/dist/pure.js' {
  declare module.exports: $Exports<'@stripe/stripe-js/dist/pure'>;
}
declare module '@stripe/stripe-js/dist/stripe.esm.js' {
  declare module.exports: $Exports<'@stripe/stripe-js/dist/stripe.esm'>;
}
declare module '@stripe/stripe-js/dist/stripe.js' {
  declare module.exports: $Exports<'@stripe/stripe-js/dist/stripe'>;
}
declare module '@stripe/stripe-js/pure.js' {
  declare module.exports: $Exports<'@stripe/stripe-js/pure'>;
}
