// flow-typed signature: 0bf6e1426377ce9bf454c3dbe4dd4528
// flow-typed version: <<STUB>>/@silvermine/videojs-chromecast_v^1.3.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@silvermine/videojs-chromecast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@silvermine/videojs-chromecast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@silvermine/videojs-chromecast/commitlint.config' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/dist/silvermine-videojs-chromecast' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/dist/silvermine-videojs-chromecast.min' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js/chromecast/ChromecastSessionManager' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js/components/ChromecastButton' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js/enableChromecast' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js/preloadWebComponents' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js/standalone' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js/tech/ChromecastTech' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-chromecast/src/js/tech/ChromecastTechUI' {
  declare module.exports: any;
}

// Filename aliases
declare module '@silvermine/videojs-chromecast/commitlint.config.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/commitlint.config'>;
}
declare module '@silvermine/videojs-chromecast/dist/silvermine-videojs-chromecast.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/dist/silvermine-videojs-chromecast'>;
}
declare module '@silvermine/videojs-chromecast/dist/silvermine-videojs-chromecast.min.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/dist/silvermine-videojs-chromecast.min'>;
}
declare module '@silvermine/videojs-chromecast/src/js/chromecast/ChromecastSessionManager.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js/chromecast/ChromecastSessionManager'>;
}
declare module '@silvermine/videojs-chromecast/src/js/components/ChromecastButton.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js/components/ChromecastButton'>;
}
declare module '@silvermine/videojs-chromecast/src/js/enableChromecast.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js/enableChromecast'>;
}
declare module '@silvermine/videojs-chromecast/src/js/index' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js'>;
}
declare module '@silvermine/videojs-chromecast/src/js/index.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js'>;
}
declare module '@silvermine/videojs-chromecast/src/js/preloadWebComponents.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js/preloadWebComponents'>;
}
declare module '@silvermine/videojs-chromecast/src/js/standalone.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js/standalone'>;
}
declare module '@silvermine/videojs-chromecast/src/js/tech/ChromecastTech.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js/tech/ChromecastTech'>;
}
declare module '@silvermine/videojs-chromecast/src/js/tech/ChromecastTechUI.js' {
  declare module.exports: $Exports<'@silvermine/videojs-chromecast/src/js/tech/ChromecastTechUI'>;
}
