// flow-typed signature: 2905db53a687f99eb09949113166d493
// flow-typed version: <<STUB>>/@silvermine/videojs-airplay_v^1.1.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@silvermine/videojs-airplay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@silvermine/videojs-airplay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@silvermine/videojs-airplay/commitlint.config' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-airplay/dist/silvermine-videojs-airplay' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-airplay/dist/silvermine-videojs-airplay.min' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-airplay/src/js/components/AirPlayButton' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-airplay/src/js/enableAirPlay' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-airplay/src/js' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-airplay/src/js/lib/hasAirPlayAPISupport' {
  declare module.exports: any;
}

declare module '@silvermine/videojs-airplay/src/js/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module '@silvermine/videojs-airplay/commitlint.config.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/commitlint.config'>;
}
declare module '@silvermine/videojs-airplay/dist/silvermine-videojs-airplay.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/dist/silvermine-videojs-airplay'>;
}
declare module '@silvermine/videojs-airplay/dist/silvermine-videojs-airplay.min.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/dist/silvermine-videojs-airplay.min'>;
}
declare module '@silvermine/videojs-airplay/src/js/components/AirPlayButton.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/src/js/components/AirPlayButton'>;
}
declare module '@silvermine/videojs-airplay/src/js/enableAirPlay.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/src/js/enableAirPlay'>;
}
declare module '@silvermine/videojs-airplay/src/js/index' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/src/js'>;
}
declare module '@silvermine/videojs-airplay/src/js/index.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/src/js'>;
}
declare module '@silvermine/videojs-airplay/src/js/lib/hasAirPlayAPISupport.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/src/js/lib/hasAirPlayAPISupport'>;
}
declare module '@silvermine/videojs-airplay/src/js/standalone.js' {
  declare module.exports: $Exports<'@silvermine/videojs-airplay/src/js/standalone'>;
}
