// flow-typed signature: 65abbe9568dbbaa9e2ffacdf3098cb18
// flow-typed version: <<STUB>>/@reach/menu-button_v0.8.6/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/menu-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/menu-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/menu-button/dist' {
  declare module.exports: any;
}

declare module '@reach/menu-button/dist/menu-button.cjs.development' {
  declare module.exports: any;
}

declare module '@reach/menu-button/dist/menu-button.cjs.production.min' {
  declare module.exports: any;
}

declare module '@reach/menu-button/dist/menu-button.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/menu-button/dist/index' {
  declare module.exports: $Exports<'@reach/menu-button/dist'>;
}
declare module '@reach/menu-button/dist/index.js' {
  declare module.exports: $Exports<'@reach/menu-button/dist'>;
}
declare module '@reach/menu-button/dist/menu-button.cjs.development.js' {
  declare module.exports: $Exports<'@reach/menu-button/dist/menu-button.cjs.development'>;
}
declare module '@reach/menu-button/dist/menu-button.cjs.production.min.js' {
  declare module.exports: $Exports<'@reach/menu-button/dist/menu-button.cjs.production.min'>;
}
declare module '@reach/menu-button/dist/menu-button.esm.js' {
  declare module.exports: $Exports<'@reach/menu-button/dist/menu-button.esm'>;
}
