// flow-typed signature: e90848ffc239733385f411ceb13a376d
// flow-typed version: <<STUB>>/@reach/rect_v^0.16.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/rect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/rect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/rect/dist/reach-rect.cjs.dev' {
  declare module.exports: any;
}

declare module '@reach/rect/dist/reach-rect.cjs' {
  declare module.exports: any;
}

declare module '@reach/rect/dist/reach-rect.cjs.prod' {
  declare module.exports: any;
}

declare module '@reach/rect/dist/reach-rect.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/rect/dist/reach-rect.cjs.dev.js' {
  declare module.exports: $Exports<'@reach/rect/dist/reach-rect.cjs.dev'>;
}
declare module '@reach/rect/dist/reach-rect.cjs.js' {
  declare module.exports: $Exports<'@reach/rect/dist/reach-rect.cjs'>;
}
declare module '@reach/rect/dist/reach-rect.cjs.prod.js' {
  declare module.exports: $Exports<'@reach/rect/dist/reach-rect.cjs.prod'>;
}
declare module '@reach/rect/dist/reach-rect.esm.js' {
  declare module.exports: $Exports<'@reach/rect/dist/reach-rect.esm'>;
}
