// flow-typed signature: 20182b8239a9fca859be3fcc3c57c8eb
// flow-typed version: <<STUB>>/@reach/tabs_v^0.1.5/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/tabs/es' {
  declare module.exports: any;
}

declare module '@reach/tabs/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/tabs/es/index' {
  declare module.exports: $Exports<'@reach/tabs/es'>;
}
declare module '@reach/tabs/es/index.js' {
  declare module.exports: $Exports<'@reach/tabs/es'>;
}
declare module '@reach/tabs/index' {
  declare module.exports: $Exports<'@reach/tabs'>;
}
declare module '@reach/tabs/index.js' {
  declare module.exports: $Exports<'@reach/tabs'>;
}
declare module '@reach/tabs/src/index' {
  declare module.exports: $Exports<'@reach/tabs/src'>;
}
declare module '@reach/tabs/src/index.js' {
  declare module.exports: $Exports<'@reach/tabs/src'>;
}
