// flow-typed signature: a04fa82cf2abccacfcef74ad7103eaa7
// flow-typed version: <<STUB>>/@reach/tooltip_v^0.12.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/tooltip/dist' {
  declare module.exports: any;
}

declare module '@reach/tooltip/dist/tooltip.cjs.development' {
  declare module.exports: any;
}

declare module '@reach/tooltip/dist/tooltip.cjs.production.min' {
  declare module.exports: any;
}

declare module '@reach/tooltip/dist/tooltip.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/tooltip/dist/index' {
  declare module.exports: $Exports<'@reach/tooltip/dist'>;
}
declare module '@reach/tooltip/dist/index.js' {
  declare module.exports: $Exports<'@reach/tooltip/dist'>;
}
declare module '@reach/tooltip/dist/tooltip.cjs.development.js' {
  declare module.exports: $Exports<'@reach/tooltip/dist/tooltip.cjs.development'>;
}
declare module '@reach/tooltip/dist/tooltip.cjs.production.min.js' {
  declare module.exports: $Exports<'@reach/tooltip/dist/tooltip.cjs.production.min'>;
}
declare module '@reach/tooltip/dist/tooltip.esm.js' {
  declare module.exports: $Exports<'@reach/tooltip/dist/tooltip.esm'>;
}
