// flow-typed signature: 2843ea621fd8124b458fbe1e50afa4a9
// flow-typed version: <<STUB>>/@reach/utils_v^0.12.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/utils/dist' {
  declare module.exports: any;
}

declare module '@reach/utils/dist/utils.cjs.development' {
  declare module.exports: any;
}

declare module '@reach/utils/dist/utils.cjs.production.min' {
  declare module.exports: any;
}

declare module '@reach/utils/dist/utils.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/utils/dist/index' {
  declare module.exports: $Exports<'@reach/utils/dist'>;
}
declare module '@reach/utils/dist/index.js' {
  declare module.exports: $Exports<'@reach/utils/dist'>;
}
declare module '@reach/utils/dist/utils.cjs.development.js' {
  declare module.exports: $Exports<'@reach/utils/dist/utils.cjs.development'>;
}
declare module '@reach/utils/dist/utils.cjs.production.min.js' {
  declare module.exports: $Exports<'@reach/utils/dist/utils.cjs.production.min'>;
}
declare module '@reach/utils/dist/utils.esm.js' {
  declare module.exports: $Exports<'@reach/utils/dist/utils.esm'>;
}
